/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Curve.FunctionFieldDVR
import Hartshorne.Curve.SeparatingParameter
import Hartshorne.Dimension.Integral
import Mathlib.RingTheory.DedekindDomain.IntegralClosure
import Mathlib.RingTheory.KrullDimension.Field
import Mathlib.RingTheory.KrullDimension.Polynomial
import Mathlib.RingTheory.Valuation.LocalSubring

/-!
# Separable normalization charts

For a one-dimensional function field `K / k`, choose a separating parameter
`t`.  The integral closures of `k[t]` and `k[t⁻¹]` in `K` are finite-type
Dedekind domains of Krull dimension one and both have fraction field `K`.
Every function-field valuation ring contains one of these two normalizations.

The intermediate fields and all embedding maps are kept inside the ambient
field `K`, so the compatibility needed by later localization arguments is
visible in the types.
-/

namespace Hartshorne

open IntermediateField
open scoped IntermediateField.algebraAdjoinAdjoin

noncomputable section

universe u v

variable (k : Type u) (K : Type v) [Field k] [Field K] [Algebra k K]

/-- One affine normalization chart associated to a transcendental element of
the function field. -/
structure SeparableNormalizationChart where
  /-- The element generating the polynomial base. -/
  parameter : K
  /-- The chart parameter is transcendental over the constant field. -/
  parameter_transcendental : Transcendental k parameter
  /-- The ambient function field is finite over the rational function field
  generated by the parameter. -/
  finiteDimensional :
    FiniteDimensional (IntermediateField.adjoin k ({parameter} : Set K)) K
  /-- The finite extension generated by the parameter is separable. -/
  isSeparable :
    Algebra.IsSeparable (IntermediateField.adjoin k ({parameter} : Set K)) K

namespace SeparableNormalizationChart

variable {k K}

/-- The polynomial base `k[t]` of a normalization chart, as a subalgebra of
the fixed ambient function field. -/
abbrev base (C : SeparableNormalizationChart k K) : Subalgebra k K :=
  Algebra.adjoin k ({C.parameter} : Set K)

/-- The fraction field `k(t)` of the polynomial base, as an intermediate field
of the fixed ambient function field. -/
abbrev intermediateField (C : SeparableNormalizationChart k K) : IntermediateField k K :=
  IntermediateField.adjoin k ({C.parameter} : Set K)

/-- The integral closure of the polynomial base inside the fixed ambient
function field. -/
abbrev normalization (C : SeparableNormalizationChart k K) : Subalgebra C.base K :=
  integralClosure C.base K

/-- The polynomial presentation `k[X] ≃ k[t]` of the chart's base. -/
noncomputable def polynomialEquiv (C : SeparableNormalizationChart k K) :
    Polynomial k ≃ₐ[k] C.base :=
  Polynomial.algEquivOfTranscendental k C.parameter C.parameter_transcendental

/-- The inclusion of the polynomial base into its fraction field. -/
def baseToIntermediateField (C : SeparableNormalizationChart k K) :
    C.base →ₐ[k] C.intermediateField :=
  Subalgebra.inclusion
    (IntermediateField.algebra_adjoin_le_adjoin k ({C.parameter} : Set K))

/-- The inclusion of the polynomial base into the ambient function field. -/
def baseToFunctionField (C : SeparableNormalizationChart k K) : C.base →ₐ[k] K :=
  C.base.val

/-- The inclusion of the rational function field into the ambient function
field. -/
def intermediateFieldToFunctionField (C : SeparableNormalizationChart k K) :
    C.intermediateField →ₐ[k] K :=
  C.intermediateField.val

/-- The algebra map from the polynomial base to its normalization. -/
def baseToNormalization (C : SeparableNormalizationChart k K) :
    C.base →+* C.normalization :=
  algebraMap C.base C.normalization

/-- The inclusion of the normalization into the ambient function field. -/
def normalizationToFunctionField (C : SeparableNormalizationChart k K) :
    C.normalization →ₐ[C.base] K :=
  C.normalization.val

@[simp]
theorem coe_polynomialEquiv_X (C : SeparableNormalizationChart k K) :
    ((C.polynomialEquiv Polynomial.X : C.base) : K) = C.parameter := by
  simp [polynomialEquiv]

@[simp]
theorem coe_baseToIntermediateField (C : SeparableNormalizationChart k K) (x : C.base) :
    ((C.baseToIntermediateField x : C.intermediateField) : K) = x :=
  rfl

@[simp]
theorem coe_baseToFunctionField (C : SeparableNormalizationChart k K) (x : C.base) :
    C.baseToFunctionField x = x :=
  rfl

@[simp]
theorem coe_intermediateFieldToFunctionField (C : SeparableNormalizationChart k K)
    (x : C.intermediateField) : C.intermediateFieldToFunctionField x = x :=
  rfl

@[simp]
theorem coe_normalizationToFunctionField (C : SeparableNormalizationChart k K)
    (x : C.normalization) : C.normalizationToFunctionField x = x :=
  rfl

/-- The base, its intermediate fraction field, and `K` form the canonical
scalar tower. -/
theorem base_intermediateField_functionField_tower
    (C : SeparableNormalizationChart k K) :
    IsScalarTower C.base C.intermediateField K := by
  infer_instance

/-- The constant field, polynomial base, and intermediate fraction field form
the canonical scalar tower. -/
theorem constants_base_intermediateField_tower
    (C : SeparableNormalizationChart k K) :
    IsScalarTower k C.base C.intermediateField := by
  infer_instance

/-- The polynomial base, its normalization, and `K` form the canonical scalar
tower. -/
theorem base_normalization_functionField_tower
    (C : SeparableNormalizationChart k K) :
    IsScalarTower C.base C.normalization K := by
  infer_instance

/-- The constant field, polynomial base, and normalization form the canonical
scalar tower. -/
theorem constants_base_normalization_tower
    (C : SeparableNormalizationChart k K) :
    IsScalarTower k C.base C.normalization := by
  infer_instance

/-- The intermediate field really is a fraction field of the polynomial
base. -/
theorem isFractionRing_intermediateField (C : SeparableNormalizationChart k K) :
    IsFractionRing C.base C.intermediateField := by
  infer_instance

instance (C : SeparableNormalizationChart k K) :
    FiniteDimensional C.intermediateField K :=
  C.finiteDimensional

instance (C : SeparableNormalizationChart k K) :
    Algebra.IsSeparable C.intermediateField K :=
  C.isSeparable

noncomputable instance (C : SeparableNormalizationChart k K) :
    IsPrincipalIdealRing C.base :=
  IsPrincipalIdealRing.of_surjective C.polynomialEquiv.toRingHom
    C.polynomialEquiv.surjective

/-- The normalization is finite as a module over its polynomial base. -/
instance (C : SeparableNormalizationChart k K) :
    Module.Finite C.base C.normalization :=
  IsIntegralClosure.finite C.base C.intermediateField K C.normalization

/-- The polynomial base is a finite-type algebra over the constant field. -/
instance (C : SeparableNormalizationChart k K) :
    Algebra.FiniteType k C.base :=
  Algebra.FiniteType.adjoin_of_finite (Set.finite_singleton C.parameter)

/-- The normalization is a finite-type algebra over the constant field. -/
instance (C : SeparableNormalizationChart k K) :
    Algebra.FiniteType k C.normalization :=
  Algebra.FiniteType.trans (S := C.base) inferInstance
    (Module.Finite.finiteType C.normalization)

/-- A separable normalization chart is a Dedekind domain. -/
instance (C : SeparableNormalizationChart k K) :
    IsDedekindDomain C.normalization :=
  IsIntegralClosure.isDedekindDomain C.base C.intermediateField K C.normalization

/-- The ambient function field is the fraction field of the normalization. -/
instance (C : SeparableNormalizationChart k K) :
    IsFractionRing C.normalization K :=
  integralClosure.isFractionRing_of_finite_extension C.intermediateField K

/-- A separable normalization chart has Krull dimension exactly one. -/
theorem ringKrullDim_normalization (C : SeparableNormalizationChart k K) :
    ringKrullDim C.normalization = 1 := by
  rw [Hartshorne.ringKrullDim_eq_of_isIntegral C.base C.normalization]
  rw [← ringKrullDim_eq_of_ringEquiv C.polynomialEquiv.toRingEquiv]
  simp

end SeparableNormalizationChart

namespace FunctionFieldDVR

variable {k K}

/-- A function-field DVR regarded as a `k`-subalgebra of its ambient field. -/
def toSubalgebra (R : FunctionFieldDVR k K) : Subalgebra k K :=
  { R.toValuationSubring.toSubring with
    algebraMap_mem' := R.algebraMap_mem }

end FunctionFieldDVR

namespace SeparableNormalizationChart

variable {k K}

/-- If a function-field DVR contains the chart parameter, it contains the
whole polynomial base. -/
theorem base_le_dvr (C : SeparableNormalizationChart k K)
    (R : FunctionFieldDVR k K) (hparameter : C.parameter ∈ R.toValuationSubring) :
    C.base ≤ R.toSubalgebra := by
  apply Algebra.adjoin_le
  intro x hx
  simp only [Set.mem_singleton_iff] at hx
  subst x
  change C.parameter ∈ R.toValuationSubring
  exact hparameter

/-- The polynomial-base embedding into a DVR which contains the chart
parameter. -/
def baseToDVR (C : SeparableNormalizationChart k K)
    (R : FunctionFieldDVR k K) (hparameter : C.parameter ∈ R.toValuationSubring) :
    C.base →+* R.toValuationSubring :=
  C.baseToFunctionField.toRingHom.codRestrict R.toValuationSubring.toSubring
    fun x => C.base_le_dvr R hparameter x.2

/-- A function-field DVR containing the chart parameter contains the entire
normalization ring. -/
theorem normalization_le_dvr (C : SeparableNormalizationChart k K)
    (R : FunctionFieldDVR k K) (hparameter : C.parameter ∈ R.toValuationSubring) :
    C.normalization.toSubring ≤ R.toValuationSubring.toSubring := by
  let _ : Algebra C.base R.toValuationSubring :=
    (C.baseToDVR R hparameter).toAlgebra
  let _ : IsScalarTower C.base R.toValuationSubring K :=
    IsScalarTower.of_algebraMap_eq fun _ => rfl
  intro x hx
  have hx_integral : IsIntegral C.base x := hx
  have hx_integral_dvr : IsIntegral R.toValuationSubring x :=
    hx_integral.tower_top
  exact LocalSubring.mem_of_isMax_of_isIntegral
    R.toValuationSubring.isMax_toLocalSubring hx_integral_dvr

end SeparableNormalizationChart

/-- The paired normalization charts at a separating parameter and its
inverse. -/
structure SeparableNormalizationCharts where
  /-- The chart based on `k[t]`. -/
  atZero : SeparableNormalizationChart k K
  /-- The chart based on `k[t⁻¹]`. -/
  atInfinity : SeparableNormalizationChart k K
  /-- The second chart uses the inverse of the first chart's parameter. -/
  infinity_parameter : atInfinity.parameter = atZero.parameter⁻¹
  /-- Both polynomial bases have the same intermediate fraction field. -/
  intermediateField_eq : atInfinity.intermediateField = atZero.intermediateField

namespace SeparableNormalizationCharts

variable {k K}

/-- Every function-field DVR contains the parameter of at least one of the two
charts. -/
theorem parameter_mem_or_inverse_mem (C : SeparableNormalizationCharts k K)
    (R : FunctionFieldDVR k K) :
    C.atZero.parameter ∈ R.toValuationSubring ∨
      C.atInfinity.parameter ∈ R.toValuationSubring := by
  rw [C.infinity_parameter]
  exact R.toValuationSubring.mem_or_inv_mem C.atZero.parameter

/-- Every function-field DVR contains one of the two normalization rings. -/
theorem normalization_cover (C : SeparableNormalizationCharts k K)
    (R : FunctionFieldDVR k K) :
    C.atZero.normalization.toSubring ≤ R.toValuationSubring.toSubring ∨
      C.atInfinity.normalization.toSubring ≤ R.toValuationSubring.toSubring := by
  rcases C.parameter_mem_or_inverse_mem R with hzero | hinfinity
  · exact Or.inl (C.atZero.normalization_le_dvr R hzero)
  · exact Or.inr (C.atInfinity.normalization_le_dvr R hinfinity)

end SeparableNormalizationCharts

/-- Choose the two finite separable normalization charts of a
one-dimensional function field. -/
noncomputable def separableNormalizationCharts
    [IsAlgClosed k] [Algebra.EssFiniteType k K]
    (htrdeg : Algebra.trdeg k K = 1) :
    SeparableNormalizationCharts k K := by
  classical
  let h := exists_separatingParameter k K htrdeg
  let t : K := h.choose
  have ht : Transcendental k t := by
    simpa [t] using h.choose_spec.1
  have hfinite :
      FiniteDimensional (IntermediateField.adjoin k ({t} : Set K)) K := by
    simpa [t] using h.choose_spec.2.1
  have hseparable :
      Algebra.IsSeparable (IntermediateField.adjoin k ({t} : Set K)) K := by
    simpa [t] using h.choose_spec.2.2.1
  have heq :
      IntermediateField.adjoin k ({t⁻¹} : Set K) =
        IntermediateField.adjoin k ({t} : Set K) := by
    simpa [t] using h.choose_spec.2.2.2
  refine
    { atZero :=
        { parameter := t
          parameter_transcendental := ht
          finiteDimensional := hfinite
          isSeparable := hseparable }
      atInfinity :=
        { parameter := t⁻¹
          parameter_transcendental := ?_
          finiteDimensional := ?_
          isSeparable := ?_ }
      infinity_parameter := rfl
      intermediateField_eq := heq }
  · rw [Transcendental, IsAlgebraic.inv_iff]
    exact ht
  · rw [heq]
    exact hfinite
  · rw [heq]
    exact hseparable

end

end Hartshorne
