/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Dimension.FgDomain
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.Algebraic.Integral
import Mathlib.Algebra.MvPolynomial.Equiv

/-!
# Adjoining a root does not change the transcendence degree

Toward Hartshorne, *Algebraic Geometry*, I.1, Theorem 1.8A(b).

For `A` a domain over `k` and `F ∈ A[X]` of positive degree, `A[X]/(F)` has the
same transcendence degree over `k` as `A` does.

This is the algebraic core of the hypersurface computation that the dimension
formula needs: cutting a polynomial ring by one irreducible polynomial costs
exactly one variable, and the reason is that the quotient is generated over the
remaining variables by a single algebraic element.

Stated for `AdjoinRoot`, which is Mathlib's name for `A[X]/(F)`, so that the
`MvPolynomial` bookkeeping — singling out a variable and viewing the polynomial
ring as a polynomial ring in it over the others — is kept separate from the
mathematics.

Positivity of the degree is used twice: it makes `A → A[X]/(F)` injective, and
it makes `F` a nonzero relation for the root.

## Main results

* `Hartshorne.injective_adjoinRoot_of`
* `Hartshorne.isAlgebraic_adjoinRoot`
* `Hartshorne.trdeg_adjoinRoot`
* `Hartshorne.trdeg_quotient_span_of_degreeOf_zero_ne_zero`
* `Hartshorne.exists_trdeg_quotient_span_irreducible`
* `Hartshorne.trdeg_fractionRing`
-/

namespace Hartshorne

open Polynomial

variable {A : Type*} [CommRing A] [IsDomain A] {F : A[X]}

/-- `A` embeds in `A[X]/(F)` when `F` has positive degree: a nonzero constant is
not divisible by something of larger degree. -/
theorem injective_adjoinRoot_of (hF : 0 < F.degree) :
    Function.Injective (AdjoinRoot.of F) := by
  rw [injective_iff_map_eq_zero]
  intro a ha
  by_contra hane
  have hdvd : F ∣ C a := by
    rw [AdjoinRoot.of, RingHom.comp_apply, AdjoinRoot.mk_eq_zero] at ha
    exact ha
  have hCa : (C a : A[X]) ≠ 0 := by simpa using hane
  have := Polynomial.degree_le_of_dvd hdvd hCa
  rw [degree_C hane] at this
  exact absurd (lt_of_lt_of_le hF this) (lt_irrefl _)

/-- `A[X]/(F)` is algebraic over `A`: it is generated by the root, and the root
satisfies the nonzero polynomial `F`. -/
theorem isAlgebraic_adjoinRoot (hF : 0 < F.degree) :
    Algebra.IsAlgebraic A (AdjoinRoot F) := by
  have hF0 : F ≠ 0 := fun h => by simp [h] at hF
  have hroot : Algebra.IsAlgebraic A (Algebra.adjoin A ({AdjoinRoot.root F} : Set _)) :=
    (Subalgebra.isAlgebraic_iff _).1
      (Algebra.isAlgebraic_adjoin_singleton_iff.2 (AdjoinRoot.isAlgebraic_root hF0))
  rw [AdjoinRoot.adjoinRoot_eq_top] at hroot
  exact Algebra.IsAlgebraic.of_injective
    (Subalgebra.topEquiv (R := A) (A := AdjoinRoot F)).symm.toAlgHom
    (Subalgebra.topEquiv (R := A) (A := AdjoinRoot F)).symm.injective

universe u

variable {k B : Type u} [Field k] [CommRing B] [IsDomain B] [Algebra k B] {G : B[X]}

/-- **Adjoining a root does not change the transcendence degree.**

The quotient must be a domain for the transcendence degree of an algebraic
extension to vanish, which is why `G` is required to cut out one. -/
theorem trdeg_adjoinRoot [IsDomain (AdjoinRoot G)] (hG : 0 < G.degree) :
    Algebra.trdeg k (AdjoinRoot G) = Algebra.trdeg k B := by
  have _ : Algebra.IsAlgebraic B (AdjoinRoot G) := isAlgebraic_adjoinRoot hG
  have _ : FaithfulSMul B (AdjoinRoot G) :=
    (faithfulSMul_iff_algebraMap_injective _ _).2 (injective_adjoinRoot_of hG)
  have h := trdeg_add_eq k B (A := AdjoinRoot G)
  rw [trdeg_eq_zero (R := B) (A := AdjoinRoot G), add_zero] at h
  exact h.symm

/-- **The hypersurface computation.**

Cutting `k[y₀,…,y_n]` by a prime principal ideal whose generator involves `y₀`
leaves transcendence degree `n`.

The polynomial ring is viewed as `k[y₁,…,y_n][y₀]` and the quotient becomes
`AdjoinRoot`, where the previous result applies. That the generator involves
`y₀` is what gives the polynomial positive degree in `y₀`. -/
theorem trdeg_quotient_span_of_degreeOf_zero_ne_zero {n : ℕ}
    {f : MvPolynomial (Fin (n + 1)) k}
    [IsDomain (MvPolynomial (Fin (n + 1)) k ⧸ Ideal.span {f})]
    (hdeg : MvPolynomial.degreeOf 0 f ≠ 0) :
    Algebra.trdeg k (MvPolynomial (Fin (n + 1)) k ⧸ Ideal.span {f}) = n := by
  classical
  set e := MvPolynomial.finSuccEquiv k n with he
  set F : Polynomial (MvPolynomial (Fin n) k) := e f with hF
  -- The generator has positive degree in the distinguished variable.
  have hFdeg : 0 < F.degree := by
    have hnat : F.natDegree = MvPolynomial.degreeOf 0 f := MvPolynomial.natDegree_finSuccEquiv f
    have hFne : F ≠ 0 := by
      intro h
      rw [h] at hnat
      exact hdeg (by simpa using hnat.symm)
    rw [Polynomial.degree_eq_natDegree hFne, hnat]
    exact_mod_cast Nat.pos_of_ne_zero hdeg
  -- The two quotients agree.
  have hmap : Ideal.span {F} = (Ideal.span {f}).map e := by
    rw [Ideal.map_span, Set.image_singleton]
  have hquot : (MvPolynomial (Fin (n + 1)) k ⧸ Ideal.span {f}) ≃ₐ[k] AdjoinRoot F :=
    Ideal.quotientEquivAlg (Ideal.span {f}) (Ideal.span {F}) e hmap
  have _ : IsDomain (AdjoinRoot F) :=
    Function.Injective.isDomain hquot.symm.toRingHom hquot.symm.injective
  rw [hquot.trdeg_eq, trdeg_adjoinRoot hFdeg]
  simp

/-- An irreducible polynomial involves some variable: a constant is either zero
or a unit. -/
theorem exists_degreeOf_ne_zero_of_irreducible {ι : Type*} {f : MvPolynomial ι k}
    (hf : Irreducible f) : ∃ i, MvPolynomial.degreeOf i f ≠ 0 := by
  classical
  by_contra hcon
  push Not at hcon
  -- Every exponent in every monomial is bounded by the corresponding `degreeOf`.
  have hsupp : ∀ m ∈ f.support, m = 0 := by
    intro m hm
    ext x
    have := MvPolynomial.monomial_le_degreeOf x hm
    rw [hcon x] at this
    simpa using this
  have htot : f.totalDegree = 0 := by
    refine Nat.le_zero.1 ?_
    rw [MvPolynomial.totalDegree]
    refine Finset.sup_le fun m hm => ?_
    rw [hsupp m hm]
    simp
  have hC := MvPolynomial.totalDegree_eq_zero_iff_eq_C.1 htot
  rcases eq_or_ne (MvPolynomial.coeff 0 f) 0 with hc | hc
  · exact hf.ne_zero (by rw [hC, hc, map_zero])
  · exact hf.not_isUnit
      (hC ▸ (isUnit_iff_ne_zero.2 hc).map (MvPolynomial.C : k →+* MvPolynomial ι k))

/-- **The hypersurface computation for an irreducible polynomial.**

`k[y₁,…,y_d]/(f)` has transcendence degree `d − 1`, stated as `n + 1 = d` so
that the drop is recorded without natural subtraction. -/
theorem exists_trdeg_quotient_span_irreducible {d : ℕ} {f : MvPolynomial (Fin d) k}
    (hf : Irreducible f) :
    ∃ n : ℕ, n + 1 = d ∧
      Algebra.trdeg k (MvPolynomial (Fin d) k ⧸ Ideal.span {f}) = n := by
  classical
  obtain ⟨i, hi⟩ := exists_degreeOf_ne_zero_of_irreducible hf
  obtain ⟨n, rfl⟩ : ∃ n, d = n + 1 := ⟨d - 1, (Nat.succ_pred_eq_of_pos i.pos).symm⟩
  refine ⟨n, rfl, ?_⟩
  -- Move the variable that occurs to the front.
  set σ : Equiv.Perm (Fin (n + 1)) := Equiv.swap i 0 with hσ
  set E := MvPolynomial.renameEquiv k σ with hE
  set g := E f with hg
  have hgdeg : MvPolynomial.degreeOf 0 g ≠ 0 := by
    have hren : MvPolynomial.degreeOf (σ i) (MvPolynomial.rename σ f)
        = MvPolynomial.degreeOf i f := MvPolynomial.degreeOf_rename_of_injective σ.injective i
    rw [hσ, Equiv.swap_apply_left] at hren
    show MvPolynomial.degreeOf 0 (MvPolynomial.rename σ f) ≠ 0
    rw [hren]
    exact hi
  have hprime : (Ideal.span {f}).IsPrime := by
    refine (Ideal.span_singleton_prime hf.ne_zero).2 ?_
    exact (UniqueFactorizationMonoid.irreducible_iff_prime).1 hf
  have hquot : (MvPolynomial (Fin (n + 1)) k ⧸ Ideal.span {f}) ≃ₐ[k]
      (MvPolynomial (Fin (n + 1)) k ⧸ Ideal.span {g}) :=
    Ideal.quotientEquivAlg (Ideal.span {f}) (Ideal.span {g}) E (by
      rw [Ideal.map_span, Set.image_singleton, hg]; rfl)
  have _ : IsDomain (MvPolynomial (Fin (n + 1)) k ⧸ Ideal.span {f}) :=
    Ideal.Quotient.isDomain _
  have _ : IsDomain (MvPolynomial (Fin (n + 1)) k ⧸ Ideal.span {g}) :=
    Function.Injective.isDomain hquot.symm.toRingHom hquot.symm.injective
  rw [hquot.trdeg_eq]
  exact trdeg_quotient_span_of_degreeOf_zero_ne_zero hgdeg

/-- Passing to the fraction field does not change the transcendence degree: a
fraction field is algebraic over its domain. -/
theorem trdeg_fractionRing (C : Type u) [CommRing C] [IsDomain C] [Algebra k C] :
    Algebra.trdeg k (FractionRing C) = Algebra.trdeg k C := by
  have _ : Algebra.IsAlgebraic C (FractionRing C) :=
    isAlgebraic_of_isFractionRing C (FractionRing C)
  have _ : FaithfulSMul C (FractionRing C) :=
    (faithfulSMul_iff_algebraMap_injective _ _).2
      (IsFractionRing.injective C (FractionRing C))
  have h := trdeg_add_eq k C (A := FractionRing C)
  rw [trdeg_eq_zero (R := C) (A := FractionRing C), add_zero] at h
  exact h.symm

/-- **The hypersurface computation, on fraction fields.** This is the form the
dimension formula consumes. -/
theorem exists_trdeg_fractionRing_quotient_span_irreducible {d : ℕ}
    {f : MvPolynomial (Fin d) k} (hf : Irreducible f) :
    ∃ n : ℕ, n + 1 = d ∧
      Algebra.trdeg k (FractionRing (MvPolynomial (Fin d) k ⧸ Ideal.span {f})) = n := by
  obtain ⟨n, hn, htr⟩ := exists_trdeg_quotient_span_irreducible hf
  have _ : (Ideal.span {f}).IsPrime :=
    (Ideal.span_singleton_prime hf.ne_zero).2
      (UniqueFactorizationMonoid.irreducible_iff_prime.1 hf)
  exact ⟨n, hn, by rw [trdeg_fractionRing]; exact htr⟩

end Hartshorne
