/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Dimension.FgDomain
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.Algebraic.Integral

/-!
# Adjoining a root does not change the transcendence degree

Toward Hartshorne, *Algebraic Geometry*, I.1, Theorem 1.8A(b).

For `A` a domain over `k` and `F ∈ A[X]` of positive degree, `A[X]/(F)` has the
same transcendence degree over `k` as `A` does.

This is the algebraic core of the hypersurface computation that the dimension
formula needs: cutting a polynomial ring by one irreducible polynomial costs
exactly one variable, and the reason is that the quotient is generated over the
remaining variables by a single algebraic element.

Stated for `AdjoinRoot`, which is Mathlib's name for `A[X]/(F)`, so that the
`MvPolynomial` bookkeeping — singling out a variable and viewing the polynomial
ring as a polynomial ring in it over the others — is kept separate from the
mathematics.

Positivity of the degree is used twice: it makes `A → A[X]/(F)` injective, and
it makes `F` a nonzero relation for the root.

## Main results

* `Hartshorne.injective_adjoinRoot_of`
* `Hartshorne.isAlgebraic_adjoinRoot`
* `Hartshorne.trdeg_adjoinRoot`
-/

namespace Hartshorne

open Polynomial

variable {A : Type*} [CommRing A] [IsDomain A] {F : A[X]}

/-- `A` embeds in `A[X]/(F)` when `F` has positive degree: a nonzero constant is
not divisible by something of larger degree. -/
theorem injective_adjoinRoot_of (hF : 0 < F.degree) :
    Function.Injective (AdjoinRoot.of F) := by
  rw [injective_iff_map_eq_zero]
  intro a ha
  by_contra hane
  have hdvd : F ∣ C a := by
    rw [AdjoinRoot.of, RingHom.comp_apply, AdjoinRoot.mk_eq_zero] at ha
    exact ha
  have hCa : (C a : A[X]) ≠ 0 := by simpa using hane
  have := Polynomial.degree_le_of_dvd hdvd hCa
  rw [degree_C hane] at this
  exact absurd (lt_of_lt_of_le hF this) (lt_irrefl _)

/-- `A[X]/(F)` is algebraic over `A`: it is generated by the root, and the root
satisfies the nonzero polynomial `F`. -/
theorem isAlgebraic_adjoinRoot (hF : 0 < F.degree) :
    Algebra.IsAlgebraic A (AdjoinRoot F) := by
  have hF0 : F ≠ 0 := fun h => by simp [h] at hF
  have hroot : Algebra.IsAlgebraic A (Algebra.adjoin A ({AdjoinRoot.root F} : Set _)) :=
    (Subalgebra.isAlgebraic_iff _).1
      (Algebra.isAlgebraic_adjoin_singleton_iff.2 (AdjoinRoot.isAlgebraic_root hF0))
  rw [AdjoinRoot.adjoinRoot_eq_top] at hroot
  exact Algebra.IsAlgebraic.of_injective
    (Subalgebra.topEquiv (R := A) (A := AdjoinRoot F)).symm.toAlgHom
    (Subalgebra.topEquiv (R := A) (A := AdjoinRoot F)).symm.injective

universe u

variable {k B : Type u} [Field k] [CommRing B] [IsDomain B] [Algebra k B] {G : B[X]}

/-- **Adjoining a root does not change the transcendence degree.**

The quotient must be a domain for the transcendence degree of an algebraic
extension to vanish, which is why `G` is required to cut out one. -/
theorem trdeg_adjoinRoot [IsDomain (AdjoinRoot G)] (hG : 0 < G.degree) :
    Algebra.trdeg k (AdjoinRoot G) = Algebra.trdeg k B := by
  have _ : Algebra.IsAlgebraic B (AdjoinRoot G) := isAlgebraic_adjoinRoot hG
  have _ : FaithfulSMul B (AdjoinRoot G) :=
    (faithfulSMul_iff_algebraMap_injective _ _).2 (injective_adjoinRoot_of hG)
  have h := trdeg_add_eq k B (A := AdjoinRoot G)
  rw [trdeg_eq_zero (R := B) (A := AdjoinRoot G), add_zero] at h
  exact h.symm

end Hartshorne
