/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Dimension.AdjoinRootTrdeg
import Hartshorne.Dimension.HeightIntegral
import Mathlib.RingTheory.Ideal.UFD
import Mathlib.Algebra.GCDMonoid.IntegrallyClosed
import Mathlib.RingTheory.Polynomial.UniqueFactorization

/-!
# A height-one prime drops the transcendence degree by one

Hartshorne, *Algebraic Geometry*, I.1, Theorem 1.8A(b), the key case.

For `B` a finitely generated domain over `k` and `𝔭 ⊆ B` a prime of height one,
`trdeg_k K(B/𝔭) + 1 = trdeg_k K(B)`.

This is the heart of the dimension formula; the general case follows from it by
induction along a maximal chain below `𝔭`.

## The argument

Take a Noether normalisation `k[y₁,…,y_s] ⊆ B` and contract `𝔭` to
`𝔮 = 𝔭 ∩ k[y]`. Then:

* `𝔮` has height one, because height is preserved by contraction along an
  integral extension of an integrally closed domain, and a polynomial ring is
  integrally closed, being a unique factorisation domain;
* so `𝔮` is principal, generated by an irreducible `f`, because a height-one
  prime of a unique factorisation domain is principal;
* so `k[y]/𝔮` has transcendence degree `s − 1`, by the hypersurface
  computation;
* and `B/𝔭` is integral over `k[y]/𝔮`, so it has the same transcendence degree.

Every one of those steps is a named result, three of them from Mathlib. The
work here is assembling them and discharging the instances.

## Main results

* `Hartshorne.exists_trdeg_of_height_eq_one`
-/

namespace Hartshorne

universe u

variable (k : Type u) [Field k]

/-- **A height-one prime drops the transcendence degree by one.** -/
theorem exists_trdeg_of_height_eq_one (B : Type u) [CommRing B] [IsDomain B] [Algebra k B]
    [Algebra.FiniteType k B] (𝔭 : Ideal B) [𝔭.IsPrime] (hht : 𝔭.height = 1) :
    ∃ n : ℕ, Algebra.trdeg k (FractionRing (B ⧸ 𝔭)) = n ∧
      Algebra.trdeg k (FractionRing B) = n + 1 := by
  obtain ⟨s, g, hinj, hint⟩ := exists_integral_inj_algHom_of_fg k B
  letI : Algebra (MvPolynomial (Fin s) k) B := g.toRingHom.toAlgebra
  haveI : IsScalarTower k (MvPolynomial (Fin s) k) B :=
    IsScalarTower.of_algebraMap_eq fun c => (g.commutes c).symm
  haveI : Algebra.IsIntegral (MvPolynomial (Fin s) k) B := ⟨hint⟩
  haveI : FaithfulSMul (MvPolynomial (Fin s) k) B :=
    (faithfulSMul_iff_algebraMap_injective _ _).2 hinj
  haveI : FiniteRingKrullDim B := finiteRingKrullDim_of_finiteType k B
  haveI : FiniteRingKrullDim (MvPolynomial (Fin s) k) :=
    finiteRingKrullDim_of_finiteType k (MvPolynomial (Fin s) k)
  set 𝔮 : Ideal (MvPolynomial (Fin s) k) := 𝔭.comap (algebraMap (MvPolynomial (Fin s) k) B)
    with h𝔮
  haveI : 𝔮.IsPrime := Ideal.comap_isPrime _ _
  haveI : IsIntegrallyClosed (MvPolynomial (Fin s) k) := inferInstance
  -- The contraction has height one too.
  have hq1 : 𝔮.height = 1 := by
    rw [h𝔮, height_comap_eq_height_of_isIntegral (MvPolynomial (Fin s) k) B 𝔭, hht]
  -- Hence it is principal, generated by an irreducible.
  obtain ⟨f, hf⟩ := (UniqueFactorizationMonoid.isPrincipal_of_height_eq_one hq1).principal
  rw [Ideal.submodule_span_eq] at hf
  have hfne : f ≠ 0 := by
    rintro rfl
    exact Ideal.ne_bot_of_height_eq_one hq1 (by simpa using hf)
  have hspanprime : (Ideal.span {f}).IsPrime := by rw [← hf]; infer_instance
  have hfirr : Irreducible f :=
    (UniqueFactorizationMonoid.irreducible_iff_prime).2
      ((Ideal.span_singleton_prime hfne).1 hspanprime)
  obtain ⟨n, hns, htr⟩ := exists_trdeg_quotient_span_irreducible hfirr
  refine ⟨n, ?_, ?_⟩
  · -- `B/𝔭` is integral over `k[y]/𝔮`, so the degrees agree.
    haveI : Algebra.IsIntegral (MvPolynomial (Fin s) k ⧸ 𝔮) (B ⧸ 𝔭) :=
      Algebra.IsIntegral.quotient
    haveI : FaithfulSMul (MvPolynomial (Fin s) k ⧸ 𝔮) (B ⧸ 𝔭) :=
      (faithfulSMul_iff_algebraMap_injective _ _).2
        (Ideal.quotientMap_injective (I := 𝔭) (f := algebraMap (MvPolynomial (Fin s) k) B))
    have htower := trdeg_add_eq k (MvPolynomial (Fin s) k ⧸ 𝔮) (A := B ⧸ 𝔭)
    rw [trdeg_eq_zero (R := MvPolynomial (Fin s) k ⧸ 𝔮) (A := B ⧸ 𝔭), add_zero] at htower
    rw [trdeg_fractionRing, ← htower, hf]
    exact htr
  · -- `dim B = s` from the same normalisation, and part (a) turns that into the degree.
    have hdimB : ringKrullDim B = (s : WithBot ℕ∞) := by
      rw [ringKrullDim_eq_of_isIntegral (MvPolynomial (Fin s) k) B,
        MvPolynomial.ringKrullDim_of_isNoetherianRing, ringKrullDim_eq_zero_of_field]
      simp
    obtain ⟨d, hdd, htd⟩ := exists_ringKrullDim_eq_trdeg k B (FractionRing B)
    have hds : d = s := by
      have : (d : WithBot ℕ∞) = (s : WithBot ℕ∞) := by rw [← hdd, hdimB]
      exact_mod_cast this
    rw [htd, hds, ← hns]
    push_cast
    ring

end Hartshorne
