/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Scheme.AdicCompletionQuotient
import Mathlib.RingTheory.AdicCompletion.AsTensorProduct

/-!
# Completed ideals and their powers

Hartshorne, *Algebraic Geometry*, II.9, Theorem 9.3A(a,b) (pp. 193--194).

For a Noetherian ring, completion of an ideal embeds in the completed ring with image equal to
the extended ideal. The same holds for every ideal power, and reduction of the completed ideal
recovers the corresponding quotient of the original ideal.
-/

noncomputable section

open Submodule TensorProduct

namespace Hartshorne

universe u

variable {A : Type u} [CommRing A] [IsNoetherianRing A]

/-- The `I`-adic completion of the ambient ring, used as the scalar ring below. -/
abbrev adicCompletionRing (I : Ideal A) := AdicCompletion I A

/-- The map from the completion of an ideal `J` to the `I`-adic completion of the ambient ring. -/
def completedIdealMap (I J : Ideal A) :
    AdicCompletion I ↥J →ₗ[adicCompletionRing I] adicCompletionRing I :=
  AdicCompletion.map I J.subtype

/-- Completion preserves the inclusion of a finite ideal into a Noetherian ring. -/
theorem completedIdealMap_injective (I J : Ideal A) :
    Function.Injective (completedIdealMap I J) :=
  AdicCompletion.map_injective I (Submodule.injective_subtype J)

/-- The image of the completed ideal is exactly its extension to the completed ring. -/
theorem completedIdealMap_range (I J : Ideal A) :
    LinearMap.range (completedIdealMap I J) =
      (J.map (algebraMap A (adicCompletionRing I))).restrictScalars
        (adicCompletionRing I) := by
  apply le_antisymm
  · rintro y ⟨x, rfl⟩
    obtain ⟨t, rfl⟩ :=
      (AdicCompletion.ofTensorProductEquivOfFiniteNoetherian I ↥J).surjective x
    have hn := AdicCompletion.ofTensorProduct_naturality I J.subtype
    change (AdicCompletion.map I J.subtype)
      (AdicCompletion.ofTensorProduct I ↥J t) ∈ _
    rw [← LinearMap.comp_apply, hn, LinearMap.comp_apply]
    induction t using TensorProduct.induction_on with
    | zero => simp
    | tmul s a =>
        rw [AlgebraTensorModule.map_tmul, LinearMap.id_apply,
          AdicCompletion.ofTensorProduct_tmul]
        apply Submodule.smul_mem
        have ha := Ideal.mem_map_of_mem (algebraMap A (adicCompletionRing I)) a.2
        simpa [AdicCompletion.algebraMap_apply] using ha
    | add x y hx hy =>
        simpa only [map_add] using Submodule.add_mem _ hx hy
  · intro y hy
    change y ∈ J.map (algebraMap A (adicCompletionRing I)) at hy
    rw [Ideal.map] at hy
    refine Submodule.span_induction
      (p := fun y _ => y ∈ LinearMap.range (completedIdealMap I J)) ?_ ?_ ?_ ?_ hy
    · rintro y ⟨a, ha, rfl⟩
      refine ⟨AdicCompletion.of I ↥J ⟨a, ha⟩, ?_⟩
      change AdicCompletion.map I J.subtype
        (AdicCompletion.of I ↥J ⟨a, ha⟩) =
          (algebraMap A (adicCompletionRing I)) a
      rw [AdicCompletion.map_of]
      simp [AdicCompletion.algebraMap_apply]
    · exact Submodule.zero_mem _
    · intro x z _ _ hx hz
      exact Submodule.add_mem _ hx hz
    · intro s x _ hx
      exact Submodule.smul_mem _ s hx

/-- The ideal `J` extended to the `I`-adic completion. -/
abbrev extendedIdeal (I J : Ideal A) :
    Submodule (adicCompletionRing I) (adicCompletionRing I) :=
  J.map (algebraMap A (adicCompletionRing I))

/-- Completion of `J` is canonically equivalent to the ideal generated by `J` in the completed
ring. -/
noncomputable def completedIdealEquiv (I J : Ideal A) :
    AdicCompletion I ↥J ≃ₗ[adicCompletionRing I] extendedIdeal I J := by
  let f := (completedIdealMap I J).codRestrict (extendedIdeal I J) (fun x => by
    change completedIdealMap I J x ∈
      (J.map (algebraMap A (adicCompletionRing I))).restrictScalars
        (adicCompletionRing I)
    rw [← completedIdealMap_range I J]
    exact LinearMap.mem_range_self _ x)
  refine LinearEquiv.ofBijective f ⟨?_, ?_⟩
  · intro x y h
    apply completedIdealMap_injective I J
    exact congrArg Subtype.val h
  · rintro ⟨y, hy⟩
    change y ∈ (J.map (algebraMap A (adicCompletionRing I))).restrictScalars
      (adicCompletionRing I) at hy
    rw [← completedIdealMap_range I J] at hy
    obtain ⟨x, rfl⟩ := hy
    exact ⟨x, rfl⟩

@[simp]
theorem completedIdealEquiv_coe (I J : Ideal A) (x : AdicCompletion I ↥J) :
    ((completedIdealEquiv I J x : extendedIdeal I J) : adicCompletionRing I) =
      completedIdealMap I J x :=
  rfl

/-- The `n`th power submodule inside the completed ideal, transported from completion of `I`. -/
noncomputable def completedIdealPower (I : Ideal A) (n : ℕ) :
    Submodule A (extendedIdeal I I) :=
  Submodule.map ((completedIdealEquiv I I).restrictScalars A).toLinearMap
    (I ^ n • (⊤ : Submodule A (AdicCompletion I ↥I)))

/-- Reduction of the completed ideal modulo its `n`th induced power recovers
`I / I^n I = I / I^(n+1)`. -/
noncomputable def completedIdealQuotientEquiv (I : Ideal A) (n : ℕ) :
    (extendedIdeal I I ⧸ completedIdealPower I n) ≃ₗ[A]
      (↥I ⧸ (I ^ n • (⊤ : Submodule A ↥I))) := by
  let E := (completedIdealEquiv I I).restrictScalars A
  let P : Submodule A (AdicCompletion I ↥I) := I ^ n • ⊤
  let Q : Submodule A (extendedIdeal I I) := Submodule.map E.toLinearMap P
  let ePQ : (AdicCompletion I ↥I ⧸ P) ≃ₗ[A] (extendedIdeal I I ⧸ Q) :=
    Submodule.Quotient.equiv P Q E rfl
  let ev := AdicCompletion.eval I ↥I n
  have hev : Function.Surjective ev := AdicCompletion.eval_surjective I ↥I n
  have hker : P = ev.ker :=
    AdicCompletion.pow_smul_top_eq_ker_eval I.fg_of_isNoetherianRing
  exact ePQ.symm.trans ((Submodule.quotEquivOfEq P ev.ker hker).trans
    (LinearMap.quotKerEquivOfSurjective ev hev))

omit [IsNoetherianRing A] in
/-- Inside the ideal `I`, multiplication by `I ^ n` is the submodule `I ^ (n + 1)`. -/
theorem pow_smul_top_ideal_eq (I : Ideal A) (n : ℕ) :
    I ^ n • (⊤ : Submodule A ↥I) =
      Submodule.comap I.subtype (I ^ (n + 1) : Ideal A) := by
  have hmapinj : Function.Injective (Submodule.map I.subtype) :=
    Submodule.map_injective_of_injective (R := A) (R₂ := A) (f := I.subtype)
      (Submodule.injective_subtype I)
  apply hmapinj
  rw [Submodule.map_smul'', Submodule.map_top, Submodule.range_subtype,
    Ideal.smul_eq_mul, pow_succ]
  rw [Submodule.map_comap_eq_self]
  simpa [Submodule.range_subtype, pow_succ] using
    (Ideal.pow_le_self (I := I) (Nat.succ_ne_zero n))

/-- The transported `n`th power inside the completed ideal embeds in the completed ring as the
extended ideal `I ^ (n + 1)`. -/
theorem completedIdealPower_map_subtype (I : Ideal A) (n : ℕ) :
    Submodule.map ((extendedIdeal I I).subtype.restrictScalars A)
        (completedIdealPower I n) =
      ((I ^ (n + 1)).map
        (algebraMap A (adicCompletionRing I))).restrictScalars A := by
  rw [completedIdealPower, ← Submodule.map_comp]
  have hcomp : ((extendedIdeal I I).subtype.restrictScalars A).comp
      ((completedIdealEquiv I I).restrictScalars A).toLinearMap =
      (completedIdealMap I I).restrictScalars A := by
    ext x
    rfl
  rw [hcomp, Submodule.map_smul'', Submodule.map_top]
  have hrange : LinearMap.range ((completedIdealMap I I).restrictScalars A) =
      (I.map (algebraMap A (adicCompletionRing I))).restrictScalars A := by
    ext x
    change x ∈ LinearMap.range (completedIdealMap I I) ↔ x ∈ _
    rw [completedIdealMap_range]
    rfl
  rw [hrange, ← Ideal.smul_restrictScalars, Ideal.smul_eq_mul, ← Ideal.map_mul]
  rw [pow_succ]

/-- The source-shaped quotient comparison
`Î / I^(n+1) Â ≃ I / I^(n+1)`. -/
noncomputable def completedIdealQuotientPowerEquiv (I : Ideal A) (n : ℕ) :
    (extendedIdeal I I ⧸ completedIdealPower I n) ≃ₗ[A]
      (↥I ⧸ Submodule.comap I.subtype (I ^ (n + 1) : Ideal A)) :=
  (completedIdealQuotientEquiv I n).trans
    (Submodule.quotEquivOfEq _ _ (pow_smul_top_ideal_eq I n))

/-- **Hartshorne II.9.3A(a,b).** Completion embeds `Î` as `I Â`, identifies completion
of every power `I ^ r` with its extension to `Â`, and gives the canonical ideal and ambient
quotient comparisons. -/
theorem completedIdealPowers (I : Ideal A) :
    Function.Injective (completedIdealMap I I) ∧
      LinearMap.range (completedIdealMap I I) = extendedIdeal I I ∧
      (∀ r : ℕ, ∃ e : AdicCompletion I ↥(I ^ r) ≃ₗ[adicCompletionRing I]
          extendedIdeal I (I ^ r),
        ∀ x, ((e x : extendedIdeal I (I ^ r)) : adicCompletionRing I) =
          completedIdealMap I (I ^ r) x) ∧
      (∀ n : ℕ,
        Submodule.map ((extendedIdeal I I).subtype.restrictScalars A)
            (completedIdealPower I n) =
          ((I ^ (n + 1)).map
            (algebraMap A (adicCompletionRing I))).restrictScalars A ∧
        Nonempty ((extendedIdeal I I ⧸ completedIdealPower I n) ≃ₗ[A]
          (↥I ⧸ Submodule.comap I.subtype (I ^ (n + 1) : Ideal A)))) ∧
      (∀ n : ℕ, ∃ e : (AdicCompletion I A ⧸
          (I ^ (n + 1)).map (algebraMap A (AdicCompletion I A))) ≃+* (A ⧸ I ^ (n + 1)),
        e.toRingHom.comp
            (Ideal.Quotient.mk
              ((I ^ (n + 1)).map (algebraMap A (AdicCompletion I A)))) =
          (AdicCompletion.evalₐ I (n + 1)).toRingHom) := by
  refine ⟨completedIdealMap_injective I I, completedIdealMap_range I I, ?_, ?_, ?_⟩
  · intro r
    exact ⟨completedIdealEquiv I (I ^ r), completedIdealEquiv_coe I (I ^ r)⟩
  · intro n
    exact ⟨completedIdealPower_map_subtype I n,
      ⟨completedIdealQuotientPowerEquiv I n⟩⟩
  · exact exists_adicCompletionQuotientRingEquiv I

end Hartshorne
