/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Basic
import Mathlib.RingTheory.Nullstellensatz
import Mathlib.RingTheory.Polynomial.Basic

/-!
# Algebraic sets in affine space

Hartshorne, *Algebraic Geometry*, I.1, pp. 1-2.

Affine `σ`-space over `k` is the function type `σ → k`; for `σ = Fin n` this is
Hartshorne's `𝔸ⁿ`. Reading a polynomial `f ∈ k[xᵢ]` as a function on it, the
*zero set* of a family `T` is the set of common zeroes, and a subset is an
*algebraic set* when it is such a zero set.

Mathlib already has this construction as `MvPolynomial.zeroLocus`, indexed by an
ideal rather than an arbitrary set and allowing the points to live in an
extension `K` of `k`. Hartshorne's case is `K = k`, so this file defines his
`Z(T)` on sets and connects it to the Mathlib development rather than repeating
it.

## Main definitions

* `Hartshorne.zeroSet` : Hartshorne's `Z(T)` for a set of polynomials `T`.
* `Hartshorne.IsAlgebraicSet` : the predicate "is a zero set".

## Main results

* `Hartshorne.zeroSet_eq_zeroLocus_span` : `Z(T)` depends only on the ideal
  generated by `T`.
* `Hartshorne.isAlgebraicSet_iff_exists_finset` : over finitely many variables
  every algebraic set is cut out by finitely many polynomials.
-/

namespace Hartshorne

open MvPolynomial

variable {k : Type*} [Field k] {σ : Type*}

/-- Hartshorne's `Z(T)`: the set of points of affine space at which every
polynomial in `T` vanishes. -/
def zeroSet (T : Set (MvPolynomial σ k)) : Set (σ → k) :=
  {x | ∀ f ∈ T, eval x f = 0}

@[simp]
theorem mem_zeroSet_iff {T : Set (MvPolynomial σ k)} {x : σ → k} :
    x ∈ zeroSet T ↔ ∀ f ∈ T, eval x f = 0 :=
  Iff.rfl

/-- `Z` reverses inclusions. -/
theorem zeroSet_anti_mono {T₁ T₂ : Set (MvPolynomial σ k)} (h : T₁ ⊆ T₂) :
    zeroSet T₂ ⊆ zeroSet T₁ :=
  fun _ hx f hf => hx f (h hf)

/-- `Z(T)` depends only on the ideal generated by `T`. This is Hartshorne's
"clearly if `𝔞` is the ideal generated by `T`, then `Z(T) = Z(𝔞)`", and it is
what lets the rest of the theory work with ideals. -/
theorem zeroSet_eq_zeroLocus_span (T : Set (MvPolynomial σ k)) :
    zeroSet T = zeroLocus k (Ideal.span T) := by
  rw [zeroLocus_span]
  ext x
  simp

/-- Zero sets of sets and zero loci of ideals are the same collection of subsets. -/
theorem zeroLocus_eq_zeroSet (I : Ideal (MvPolynomial σ k)) :
    zeroLocus k I = zeroSet (I : Set (MvPolynomial σ k)) := by
  rw [zeroSet_eq_zeroLocus_span, Ideal.span_eq]

/-- A subset of affine space is an *algebraic set* when it is the common zero set
of some family of polynomials. -/
def IsAlgebraicSet (Y : Set (σ → k)) : Prop :=
  ∃ T : Set (MvPolynomial σ k), Y = zeroSet T

theorem isAlgebraicSet_zeroSet (T : Set (MvPolynomial σ k)) :
    IsAlgebraicSet (zeroSet T) :=
  ⟨T, rfl⟩

/-- An algebraic set is cut out by an ideal, and conversely. -/
theorem isAlgebraicSet_iff_exists_ideal {Y : Set (σ → k)} :
    IsAlgebraicSet Y ↔ ∃ I : Ideal (MvPolynomial σ k), Y = zeroLocus k I := by
  constructor
  · rintro ⟨T, rfl⟩
    exact ⟨Ideal.span T, zeroSet_eq_zeroLocus_span T⟩
  · rintro ⟨I, rfl⟩
    exact ⟨(I : Set (MvPolynomial σ k)), zeroLocus_eq_zeroSet I⟩

section Finite

variable [Finite σ]

/-- Over finitely many variables the polynomial ring is Noetherian, so every
algebraic set is the zero set of a *finite* family. Hartshorne draws this
consequence immediately after the definition. -/
theorem isAlgebraicSet_iff_exists_finset {Y : Set (σ → k)} :
    IsAlgebraicSet Y ↔ ∃ s : Finset (MvPolynomial σ k), Y = zeroSet (s : Set _) := by
  refine ⟨?_, fun ⟨s, hs⟩ => ⟨(s : Set _), hs⟩⟩
  rintro ⟨T, rfl⟩
  obtain ⟨s, hs⟩ := (isNoetherianRing_iff_ideal_fg (MvPolynomial σ k)).1
    inferInstance (Ideal.span T)
  refine ⟨s, ?_⟩
  rw [zeroSet_eq_zeroLocus_span, zeroSet_eq_zeroLocus_span, hs]

end Finite

end Hartshorne
