/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.RingTheory.GradedAlgebra.Radical

/-!
# Homogeneous ideals

Hartshorne, *Algebraic Geometry*, I.2, the graded-ring paragraph on p. 9.

Hartshorne recalls graded rings and homogeneous ideals and quotes, without
proof, that an ideal is homogeneous iff generated by homogeneous elements, that
sums, products, intersections and radicals of homogeneous ideals are
homogeneous, and that primeness can be tested on homogeneous elements alone.

All of that is in Mathlib, for a general `GradedAlgebra`. This file does the two
things that are actually needed: it makes the total-degree grading on
`k[x₀,…,xₙ]` available as a scoped instance, and it reconciles Mathlib's two
notions of "homogeneous element" — `MvPolynomial.IsHomogeneous`, which the
affine and projective files use, and `IsHomogeneousElem` of the graded algebra,
which the ideal-theoretic lemmas are stated against.

## Main results

* `Hartshorne.isHomogeneousElem_iff` : the two notions agree.
* `Hartshorne.IsHomogeneousIdeal.radical` and
  `Hartshorne.IsHomogeneousIdeal.isPrime_iff` : Hartshorne's quoted facts,
  specialised.
-/

namespace Hartshorne

open MvPolynomial

variable {k : Type*} [CommRing k] {σ : Type*}

-- The grading of `k[x₀,…,xₙ]` by total degree. Mathlib provides this only as a
-- local instance, since a polynomial ring carries other gradings. Chapter I
-- uses this one throughout, so it is scoped to the `Hartshorne` namespace
-- rather than enabled globally.
attribute [scoped instance] MvPolynomial.gradedAlgebra

/-- An ideal of the polynomial ring is *homogeneous* when it is homogeneous for
the total-degree grading. -/
abbrev IsHomogeneousIdeal (I : Ideal (MvPolynomial σ k)) : Prop :=
  I.IsHomogeneous (homogeneousSubmodule σ k)

/-- Mathlib's graded-algebra notion of a homogeneous element agrees with
`MvPolynomial.IsHomogeneous` for the total-degree grading.

The ideal lemmas below are stated with `IsHomogeneousElem`, while the affine and
projective files speak of `IsHomogeneous`; without this bridge the two halves of
the development cannot be combined. -/
theorem isHomogeneousElem_iff {f : MvPolynomial σ k} :
    SetLike.IsHomogeneousElem (homogeneousSubmodule σ k) f ↔ ∃ n, f.IsHomogeneous n := by
  constructor
  · rintro ⟨n, hn⟩
    exact ⟨n, (mem_homogeneousSubmodule n f).1 hn⟩
  · rintro ⟨n, hn⟩
    exact ⟨n, (mem_homogeneousSubmodule n f).2 hn⟩

/-- Hartshorne's quoted fact: the radical of a homogeneous ideal is
homogeneous. -/
theorem IsHomogeneousIdeal.radical {I : Ideal (MvPolynomial σ k)}
    (h : IsHomogeneousIdeal I) : IsHomogeneousIdeal I.radical :=
  Ideal.IsHomogeneous.radical h

/-- Hartshorne's quoted fact: primeness of a homogeneous ideal can be tested on
homogeneous elements alone. -/
theorem IsHomogeneousIdeal.isPrime_iff {I : Ideal (MvPolynomial σ k)}
    (h : IsHomogeneousIdeal I) :
    I.IsPrime ↔ I ≠ ⊤ ∧ ∀ {x y : MvPolynomial σ k},
      (∃ m, x.IsHomogeneous m) → (∃ n, y.IsHomogeneous n) → x * y ∈ I → x ∈ I ∨ y ∈ I := by
  rw [Ideal.IsHomogeneous.isPrime_iff h]
  refine and_congr_right fun _ => ?_
  constructor
  · exact fun H _ _ hx hy => H (isHomogeneousElem_iff.2 hx) (isHomogeneousElem_iff.2 hy)
  · exact fun H _ _ hx hy => H (isHomogeneousElem_iff.1 hx) (isHomogeneousElem_iff.1 hy)

end Hartshorne
