/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Projective.Nullstellensatz
import Hartshorne.Affine.Correspondence

/-!
# The irrelevant ideal, and when `Z(𝔞)` is empty

Hartshorne, *Algebraic Geometry*, I.2, Exercise 2.2 (p. 11).

The *irrelevant ideal* `S₊ = ⨁_{d>0} S_d` is the one homogeneous radical ideal
that the correspondence of Exercise 2.4 has to leave out: it is proper, but its
projective zero set is empty, and `∅` already corresponds to `S`.

Exercise 2.2 identifies exactly which ideals have empty zero set: `Z(𝔞) = ∅`
precisely when `√𝔞` contains `S₊`. The proof goes through the affine cone —
`Z(𝔞)` is empty exactly when the affine zero set of `𝔞` is contained in the
origin — and then applies the affine Nullstellensatz.

Mathlib does not have that the polynomials with vanishing constant term are the
span of the variables, so that is proved here.

## Main definitions

* `Hartshorne.irrelevantIdeal`

## Main results

* `Hartshorne.vanishingIdeal_singleton_zero` : `S₊` is the ideal of the origin.
* `Hartshorne.projZeroSet_eq_empty_iff` : Exercise 2.2.
-/

namespace Hartshorne

open MvPolynomial

variable {k : Type*} [Field k] {σ : Type*}

/-- The *irrelevant ideal* `S₊`, generated by the variables. -/
noncomputable def irrelevantIdeal (k σ : Type*) [Field k] : Ideal (MvPolynomial σ k) :=
  Ideal.span (Set.range X)

theorem X_mem_irrelevantIdeal (j : σ) : (X j : MvPolynomial σ k) ∈ irrelevantIdeal k σ :=
  Ideal.subset_span ⟨j, rfl⟩

/-- Subtracting its value at the origin puts any polynomial in the irrelevant
ideal. Proved by induction; the multiplication case is where a variable appears
and the constant term dies. -/
theorem sub_C_eval_zero_mem_irrelevantIdeal (f : MvPolynomial σ k) :
    f - C (eval (0 : σ → k) f) ∈ irrelevantIdeal k σ := by
  induction f using MvPolynomial.induction_on with
  | C a => simp
  | add p q hp hq =>
      have : p + q - C (eval (0 : σ → k) (p + q))
          = (p - C (eval (0 : σ → k) p)) + (q - C (eval (0 : σ → k) q)) := by
        rw [map_add, map_add]; ring
      rw [this]
      exact Ideal.add_mem _ hp hq
  | mul_X p j _ =>
      have : p * X j - C (eval (0 : σ → k) (p * X j)) = p * X j := by
        simp
      rw [this]
      exact Ideal.mul_mem_left _ _ (X_mem_irrelevantIdeal j)

/-- The irrelevant ideal is exactly the ideal of the origin. -/
theorem vanishingIdeal_singleton_zero :
    vanishingIdeal k ({0} : Set (σ → k)) = irrelevantIdeal k σ := by
  refine le_antisymm (fun f hf => ?_) (Ideal.span_le.2 ?_)
  · have h0 : eval (0 : σ → k) f = 0 := by simpa using hf 0 rfl
    have hmem := sub_C_eval_zero_mem_irrelevantIdeal f
    rwa [h0, map_zero, sub_zero] at hmem
  · rintro _ ⟨j, rfl⟩
    show (X j : MvPolynomial σ k) ∈ vanishingIdeal k ({0} : Set (σ → k))
    intro x hx
    rw [Set.mem_singleton_iff.1 hx]
    simp

/-- The affine zero set of the irrelevant ideal is the origin. -/
theorem zeroSet_irrelevantIdeal :
    zeroSet ((irrelevantIdeal k σ : Ideal (MvPolynomial σ k)) : Set (MvPolynomial σ k))
      = {0} := by
  ext v
  simp only [mem_zeroSet_iff, Set.mem_singleton_iff]
  constructor
  · intro h
    funext j
    simpa using h (X j) (X_mem_irrelevantIdeal j)
  · rintro rfl f hf
    have := (vanishingIdeal_singleton_zero (k := k) (σ := σ)) ▸ hf
    simpa using this (0 : σ → k) rfl

section AlgClosed

variable [IsAlgClosed k] [Finite σ]

/-- A projective zero set is empty exactly when the affine zero set is contained
in the origin. This is the cone picture: nonzero affine zeros are precisely the
representatives of projective zeros. -/
theorem projZeroSet_eq_empty_iff_zeroSet_subset {I : Ideal (MvPolynomial σ k)}
    (hI : IsHomogeneousIdeal I) :
    projZeroSet (I : Set (MvPolynomial σ k)) = ∅ ↔
      zeroSet (I : Set (MvPolynomial σ k)) ⊆ {0} := by
  constructor
  · intro h v hv
    by_contra hv0
    have hmem : Projectivization.mk k v hv0 ∈ projZeroSet (I : Set (MvPolynomial σ k)) := by
      intro g hg
      obtain ⟨a, ha⟩ := Projectivization.exists_smul_eq_mk_rep k v hv0
      show eval _ g = 0
      rw [← ha, Units.smul_def]
      exact zeroSet_smul_of_isHomogeneousIdeal hI hv g hg
    rw [h] at hmem
    exact hmem
  · intro h
    rw [Set.eq_empty_iff_forall_notMem]
    intro P hP
    have hrep : P.rep ∈ zeroSet (I : Set (MvPolynomial σ k)) := fun g hg => hP g hg
    exact P.rep_nonzero (h hrep)

/-- **Exercise 2.2**: the projective zero set of a homogeneous ideal is empty
exactly when its radical contains the irrelevant ideal. -/
theorem projZeroSet_eq_empty_iff {I : Ideal (MvPolynomial σ k)}
    (hI : IsHomogeneousIdeal I) :
    projZeroSet (I : Set (MvPolynomial σ k)) = ∅ ↔ irrelevantIdeal k σ ≤ I.radical := by
  rw [projZeroSet_eq_empty_iff_zeroSet_subset hI, ← vanishingIdeal_singleton_zero,
    ← vanishingIdeal_zeroSet_eq_radical]
  constructor
  · exact fun h => vanishingIdeal_anti_mono h
  · intro h
    have hz : zeroSet ((vanishingIdeal k (zeroSet (I : Set (MvPolynomial σ k)))
        : Ideal (MvPolynomial σ k)) : Set (MvPolynomial σ k))
        ⊆ zeroSet ((vanishingIdeal k ({0} : Set (σ → k))
          : Ideal (MvPolynomial σ k)) : Set (MvPolynomial σ k)) := by
      intro x hx f hf
      exact hx f (h hf)
    have h1 : zeroSet ((vanishingIdeal k (zeroSet (I : Set (MvPolynomial σ k)))
        : Ideal (MvPolynomial σ k)) : Set (MvPolynomial σ k))
        = zeroSet (I : Set (MvPolynomial σ k)) := by
      rw [← zeroLocus_eq_zeroSet, ← zeroLocus_eq_zeroSet]
      exact (isAlgebraicSet_iff_exists_ideal.2 ⟨I, rfl⟩).zeroLocus_vanishingIdeal
    have h2 : zeroSet ((vanishingIdeal k ({0} : Set (σ → k))
        : Ideal (MvPolynomial σ k)) : Set (MvPolynomial σ k)) = {0} := by
      rw [vanishingIdeal_singleton_zero]
      exact zeroSet_irrelevantIdeal
    rw [h1, h2] at hz
    exact hz

end AlgClosed

end Hartshorne
