/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Projective.CoordAwayChart
import Hartshorne.Projective.Correspondence

/-!
# The homogeneous prime at a point

Toward Hartshorne, *Algebraic Geometry*, I.3, Theorem 3.4(b).

`𝔪_P`, the ideal of `S(Y)` generated by the homogeneous elements vanishing at a
point `P ∈ Y`, together with the three facts Theorem 3.4(b) needs about it: it is
prime, it is homogeneous, and it misses the class of `xᵢ` when `P` lies in the
chart `Uᵢ`.

Hartshorne names `𝔪_P` in the statement of 3.4(b) and says nothing else about
it. The three facts are what the graded comparison
`S_(𝔪_P) = (S_(xᵢ))_𝔮` requires of its prime, and none of them is free: the
`𝔭 = (0)` case that finished part (c) needed no construction at all.

The route is through `J({P})` upstairs rather than `𝔪_P` downstairs. Primality
is then Hartshorne's quoted fact that a homogeneous ideal can be tested on
homogeneous elements — for a single point the test is that `k` is a domain —
and everything transfers because `J(Y) ≤ J({P})`, so the quotient map neither
adds nor loses membership.

## Main definitions

* `Hartshorne.projPointIdeal`

## Main results

* `Hartshorne.isPrime_projPointIdeal`, `Hartshorne.isHomogeneous_projPointIdeal`
* `Hartshorne.mk_X_notMem_projPointIdeal`
-/

namespace Hartshorne

open MvPolynomial

variable {k : Type*} [Field k] {σ : Type*}

/-- For a homogeneous `f`, lying in `J({P})` is vanishing at `P`. -/
theorem mem_homogeneousVanishingIdeal_singleton_iff {n : ℕ} {f : MvPolynomial σ k}
    (hf : f.IsHomogeneous n) (P : ProjectiveSpace k σ) :
    f ∈ homogeneousVanishingIdeal ({P} : Set (ProjectiveSpace k σ))
      ↔ HomogeneousVanish f P := by
  refine ⟨fun h => homogeneousVanish_of_mem_homogeneousVanishingIdeal h rfl, fun h => ?_⟩
  exact Ideal.subset_span ⟨⟨n, hf⟩, fun Q hQ => by rwa [show Q = P from hQ]⟩

/-- `J({P})` is prime. On homogeneous elements the condition is that a product
of values in `k` vanishes, and `k` is a field. -/
theorem isPrime_homogeneousVanishingIdeal_singleton (P : ProjectiveSpace k σ) :
    (homogeneousVanishingIdeal ({P} : Set (ProjectiveSpace k σ))).IsPrime := by
  refine (IsHomogeneousIdeal.isPrime_iff
    (isHomogeneousIdeal_homogeneousVanishingIdeal _)).2 ⟨?_, ?_⟩
  · intro htop
    have h1 : (1 : MvPolynomial σ k) ∈ homogeneousVanishingIdeal ({P} : Set _) := by
      rw [htop]; trivial
    have hv := homogeneousVanish_of_mem_homogeneousVanishingIdeal h1 rfl
    simp [HomogeneousVanish] at hv
  · rintro x y ⟨m, hx⟩ ⟨n, hy⟩ hxy
    rw [mem_homogeneousVanishingIdeal_singleton_iff (hx.mul hy)] at hxy
    have hxy' : eval P.rep x * eval P.rep y = 0 := by
      rw [← map_mul]; exact hxy
    rcases mul_eq_zero.1 hxy' with h | h
    · exact Or.inl ((mem_homogeneousVanishingIdeal_singleton_iff hx P).2 h)
    · exact Or.inr ((mem_homogeneousVanishingIdeal_singleton_iff hy P).2 h)

variable (Y : Set (ProjectiveSpace k σ)) (P : ProjectiveSpace k σ)

/-- **`𝔪_P`**: the ideal of `S(Y)` generated by the homogeneous elements
vanishing at `P`, obtained by pushing `J({P})` down. -/
noncomputable def projPointIdeal : Ideal (homogeneousCoordinateRing Y) :=
  (homogeneousVanishingIdeal ({P} : Set (ProjectiveSpace k σ))).map
    (Ideal.Quotient.mk (homogeneousVanishingIdeal Y))

variable {Y P}

/-- Membership in `𝔪_P` is membership in `J({P})` upstairs, since the kernel of
the quotient map is contained in `J({P})`. -/
theorem mem_projPointIdeal_iff (hP : P ∈ Y) {g : MvPolynomial σ k} :
    (Ideal.Quotient.mk (homogeneousVanishingIdeal Y) g) ∈ projPointIdeal Y P
      ↔ g ∈ homogeneousVanishingIdeal ({P} : Set (ProjectiveSpace k σ)) := by
  have hle : homogeneousVanishingIdeal Y
      ≤ homogeneousVanishingIdeal ({P} : Set (ProjectiveSpace k σ)) :=
    homogeneousVanishingIdeal_anti_mono (Set.singleton_subset_iff.2 hP)
  constructor
  · intro h
    have hcomap : Ideal.comap (Ideal.Quotient.mk (homogeneousVanishingIdeal Y))
        (projPointIdeal Y P)
        = homogeneousVanishingIdeal ({P} : Set (ProjectiveSpace k σ)) := by
      rw [projPointIdeal, Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
        ← RingHom.ker_eq_comap_bot, Ideal.mk_ker, sup_eq_left.2 hle]
    exact hcomap ▸ h
  · exact fun h => Ideal.mem_map_of_mem _ h

/-- `𝔪_P` is prime, `J({P})` being prime and containing the kernel. -/
theorem isPrime_projPointIdeal (hP : P ∈ Y) : (projPointIdeal Y P).IsPrime := by
  have := isPrime_homogeneousVanishingIdeal_singleton P
  refine Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective ?_
  rw [Ideal.mk_ker]
  exact homogeneousVanishingIdeal_anti_mono (Set.singleton_subset_iff.2 hP)

/-- `𝔪_P` is homogeneous: it is spanned by the images of homogeneous
polynomials, and the image of a homogeneous element is homogeneous for the
quotient grading. -/
theorem isHomogeneous_projPointIdeal :
    Ideal.IsHomogeneous (projCoordGrading Y) (projPointIdeal Y P) := by
  show Ideal.IsHomogeneous (projCoordGrading Y)
    (Ideal.map (Ideal.Quotient.mk (homogeneousVanishingIdeal Y))
      (Ideal.span (homogeneousVanishingSet ({P} : Set (ProjectiveSpace k σ)))))
  rw [Ideal.map_span]
  refine Ideal.homogeneous_span _ _ ?_
  rintro _ ⟨g, ⟨⟨n, hg⟩, -⟩, rfl⟩
  exact ⟨n, ⟨g, (mem_homogeneousSubmodule n g).2 hg, rfl⟩⟩

/-- The class of `xᵢ` avoids `𝔪_P` when `P` lies in the chart: `xᵢ` does not
vanish at `P`. -/
theorem mk_X_notMem_projPointIdeal (hP : P ∈ Y) (i : σ) (hPc : P ∈ standardChart i) :
    (Ideal.Quotient.mk (projVanishingIdeal Y).toIdeal (X i)) ∉ projPointIdeal Y P := by
  rw [mem_projPointIdeal_iff hP,
    mem_homogeneousVanishingIdeal_singleton_iff (isHomogeneous_X k i)]
  intro h
  exact rep_ne_zero_of_mem_standardChart hPc (by simpa [HomogeneousVanish] using h)

end Hartshorne
