/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Projective.Zariski
import Hartshorne.Projective.HomogeneousIdeal

/-!
# The homogeneous vanishing ideal

Hartshorne, *Algebraic Geometry*, I.2, the definitions on p. 10 with
Exercise 2.3.

For `Y ⊆ ℙⁿ` the *homogeneous ideal* `J(Y)` is generated by the homogeneous
polynomials vanishing on `Y`, and the *homogeneous coordinate ring* is
`S(Y) = S/J(Y)`.

Unlike `A(Y)` in the affine case, `S(Y)` is not an invariant of the variety: it
depends on the chosen embedding into projective space. That is why Theorem 3.4
describes `𝒪_P` and `K(Y)` through graded localizations of `S(Y)` rather than
identifying `S(Y)` itself with anything intrinsic.

## Main definitions

* `Hartshorne.homogeneousVanishingIdeal`
* `Hartshorne.homogeneousCoordinateRing`

## Main results

* `Hartshorne.projZeroSet_span` : `Z(T)` depends only on the ideal `T` spans.
* `Hartshorne.projZeroSet_homogeneousVanishingIdeal_eq_closure` : Exercise
  2.3(e), `Z(J(Y)) = Ȳ`.
-/

namespace Hartshorne

open MvPolynomial

variable {k : Type*} [Field k] {σ : Type*}

/-- `Z(T)` depends only on the ideal generated by `T`. Everything is evaluated
at one chosen representative, so this needs no homogeneity hypothesis. -/
theorem projZeroSet_span (T : Set (MvPolynomial σ k)) :
    projZeroSet (Ideal.span T : Set (MvPolynomial σ k)) = projZeroSet T := by
  refine le_antisymm (projZeroSet_anti_mono Ideal.subset_span) ?_
  intro P hP f hf
  refine Submodule.span_induction (p := fun g _ => HomogeneousVanish g P) ?_ ?_ ?_ ?_ hf
  · exact fun g hg => hP g hg
  · show eval P.rep 0 = 0
    simp
  · intro g h _ _ hg hh
    show eval P.rep (g + h) = 0
    rw [map_add, hg, hh, add_zero]
  · intro a g _ hg
    show eval P.rep (a • g) = 0
    rw [smul_eq_mul, map_mul, hg, mul_zero]

/-- Hartshorne's `J(Y)`: the ideal generated by the homogeneous polynomials
vanishing on `Y`. -/
noncomputable def homogeneousVanishingIdeal (Y : Set (ProjectiveSpace k σ)) :
    Ideal (MvPolynomial σ k) :=
  Ideal.span (homogeneousVanishingSet Y)

/-- `J(Y)` is a homogeneous ideal, being generated by homogeneous elements. -/
theorem isHomogeneousIdeal_homogeneousVanishingIdeal (Y : Set (ProjectiveSpace k σ)) :
    IsHomogeneousIdeal (homogeneousVanishingIdeal Y) :=
  Ideal.homogeneous_span _ _ fun f hf => isHomogeneousElem_iff.2 hf.1

/-- The *homogeneous coordinate ring* `S(Y) = S/J(Y)`. -/
abbrev homogeneousCoordinateRing (Y : Set (ProjectiveSpace k σ)) : Type _ :=
  MvPolynomial σ k ⧸ homogeneousVanishingIdeal Y

/-- Exercise 2.3(b): `J` reverses inclusions. -/
theorem homogeneousVanishingIdeal_anti_mono {Y₁ Y₂ : Set (ProjectiveSpace k σ)}
    (h : Y₁ ⊆ Y₂) : homogeneousVanishingIdeal Y₂ ≤ homogeneousVanishingIdeal Y₁ :=
  Ideal.span_mono fun _ hf => ⟨hf.1, fun P hP => hf.2 P (h hP)⟩

/-- `Z(J(Y)) = Z` of the homogeneous polynomials vanishing on `Y`. -/
theorem projZeroSet_homogeneousVanishingIdeal (Y : Set (ProjectiveSpace k σ)) :
    projZeroSet (homogeneousVanishingIdeal Y : Set (MvPolynomial σ k))
      = projZeroSet (homogeneousVanishingSet Y) :=
  projZeroSet_span _

/-- Projective algebraic sets are closed. -/
theorem isClosed_projZeroSet_of_isHomogeneousSet {T : Set (MvPolynomial σ k)}
    (hT : IsHomogeneousSet T) : IsClosed (projZeroSet T) :=
  isClosed_iff_isProjAlgebraicSet.2 ⟨T, hT, rfl⟩

/-- **Exercise 2.3(e)**: `Z(J(Y))` is the closure of `Y`.

So, as in the affine case, `Z ∘ J` is the closure operator of the Zariski
topology and the algebraic sets are its fixed points. -/
theorem projZeroSet_homogeneousVanishingIdeal_eq_closure (Y : Set (ProjectiveSpace k σ)) :
    projZeroSet (homogeneousVanishingIdeal Y : Set (MvPolynomial σ k)) = closure Y := by
  rw [projZeroSet_homogeneousVanishingIdeal]
  refine le_antisymm ?_ (closure_minimal (subset_projZeroSet_homogeneousVanishingSet Y)
    (isClosed_projZeroSet_of_isHomogeneousSet
      (isHomogeneousSet_homogeneousVanishingSet Y)))
  calc projZeroSet (homogeneousVanishingSet Y)
      ⊆ projZeroSet (homogeneousVanishingSet (closure Y)) :=
        projZeroSet_anti_mono fun f hf => ⟨hf.1, fun P hP => hf.2 P (subset_closure hP)⟩
    _ = closure Y :=
        (isClosed_iff_isProjAlgebraicSet.1 isClosed_closure).projZeroSet_homogeneousVanishingSet

end Hartshorne
