/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Affine.CoordinateRing
import Hartshorne.Affine.Decomposition
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic

/-!
# Affine components and minimal primes

Hartshorne, *Algebraic Geometry*, I.7, proof of Proposition 7.1 (p. 48).

If `W` is an irreducible component of the intersection of an affine variety
`X` with the zero set of a family of polynomials, then the relative ideal of
`W` in `A(X)` is a minimal prime over the ideal generated by those equations.
-/

namespace Hartshorne

open MvPolynomial

variable {k : Type*} [Field k] {σ : Type*}

/-- The relative ideal of `W` in the coordinate ring of `X`. -/
noncomputable def componentIdeal (X W : Set (σ → k)) : Ideal (coordinateRing X) :=
  (vanishingIdeal k W).map (Ideal.Quotient.mk (vanishingIdeal k X))

section AlgClosed

variable [IsAlgClosed k] [Finite σ]

/-- An irreducible component of a closed affine cut corresponds to a minimal
prime over the ideal generated by the cutting equations in the coordinate
ring. -/
theorem componentIdeal_mem_minimalPrimes {X W : Set (σ → k)}
    (hX : IsAffineVariety X) (T : Finset (MvPolynomial σ k))
    (hW : Maximal
      (fun V : Set (σ → k) =>
        IsAffineVariety V ∧ V ⊆ X ∩ zeroSet (T : Set (MvPolynomial σ k))) W) :
    componentIdeal X W ∈
      (Ideal.span
        (Ideal.Quotient.mk (vanishingIdeal k X) '' (T : Set (MvPolynomial σ k)))).minimalPrimes := by
  classical
  let f := Ideal.Quotient.mk (vanishingIdeal k X)
  have hWX : W ⊆ X := fun _ hx => (hW.1.2 hx).1
  have hXI_WI : vanishingIdeal k X ≤ vanishingIdeal k W :=
    vanishingIdeal_anti_mono hWX
  have hWI_prime : (vanishingIdeal k W).IsPrime :=
    (isIrreducible_iff_isPrime hW.1.1.isAlgebraicSet).1 hW.1.1.isIrreducible
  let _ : (vanishingIdeal k W).IsPrime := hWI_prime
  have hcomponent_prime : (componentIdeal X W).IsPrime := by
    simpa only [componentIdeal] using
      (Ideal.isPrime_map_quotientMk_of_isPrime hXI_WI)
  refine ⟨⟨hcomponent_prime, ?_⟩, ?_⟩
  · rw [componentIdeal, Ideal.span_le]
    rintro _ ⟨t, ht, rfl⟩
    exact Ideal.mem_map_of_mem _ (fun x hx => (hW.1.2 hx).2 t ht)
  · intro Q hQ hQ_le
    let _ : Q.IsPrime := hQ.1
    have hXQ : vanishingIdeal k X ≤ Q.comap f := by
      simpa only [f, Ideal.mk_ker] using
        (Ideal.ker_le_comap (K := Q) f)
    have hQW : Q.comap f ≤ vanishingIdeal k W := by
      have h := Ideal.comap_mono (f := f) hQ_le
      simpa only [f, componentIdeal, Ideal.comap_map_mk hXI_WI] using h
    let V : Set (σ → k) := zeroLocus k (Q.comap f)
    have hVvariety : IsAffineVariety V := by
      exact isAffineVariety_zeroLocus_of_isPrime (Ideal.comap_isPrime f Q)
    have hWV : W ⊆ V := by
      exact le_zeroLocus_iff_le_vanishingIdeal.2 hQW
    have hVX : V ⊆ X := by
      rw [← hX.isAlgebraicSet.zeroLocus_vanishingIdeal]
      exact zeroLocus_anti_mono hXQ
    have hVT : V ⊆ zeroSet T := by
      intro x hx t ht
      exact hx t (show t ∈ Q.comap f from
        hQ.2 (Ideal.subset_span ⟨t, ht, rfl⟩))
    have hVW : V ⊆ W :=
      hW.2 ⟨hVvariety, fun x hx => ⟨hVX hx, hVT hx⟩⟩ hWV
    have hVW_eq : V = W := Set.Subset.antisymm hVW hWV
    have hIWQ : vanishingIdeal k W = Q.comap f := by
      rw [← hVW_eq]
      exact vanishingIdeal_zeroLocus_of_isPrime (Ideal.comap_isPrime f Q)
    rw [componentIdeal, hIWQ]
    exact (Ideal.map_comap_of_surjective f Ideal.Quotient.mk_surjective Q).le

end AlgClosed

end Hartshorne
