/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Intersection.GradedSubquotient
import Mathlib.Algebra.Module.Torsion.Basic

/-!
# Homogeneous annihilators and cyclic graded modules

Hartshorne, *Algebraic Geometry*, I.7, Proposition 7.4 (pp. 50–51).

The annihilator of an integer-graded module is homogeneous.  If `m` is
homogeneous of degree `l`, the ordinary cyclic-module equivalence
`A / Ann(m) ≃ A · m` respects the grading after twisting the quotient by
`-l`.
-/

namespace Hartshorne

open DirectSum

noncomputable section

variable {R A M : Type*}
  [CommRing R] [CommRing A] [Algebra R A]
  [AddCommGroup M] [Module R M] [Module A M] [IsScalarTower R A M]
  (𝓐 : ℤ → Submodule R A) [GradedAlgebra 𝓐]
  (ℳ : ℤ → Submodule R M) [DirectSum.Decomposition ℳ]
  [SetLike.GradedSMul 𝓐 ℳ]

omit [IsScalarTower R A M] in
/-- The degree-`d` component of a scalar multiple of a homogeneous vector of
degree `e` uses only the degree-`d-e` component of the scalar. -/
private theorem coe_decompose_smul_of_mem
    (a : A) {e d : ℤ} {m : M} (hm : m ∈ ℳ e) :
    ((DirectSum.decompose ℳ (a • m) d : ℳ d) : M) =
      (DirectSum.decompose 𝓐 a (d - e) : A) • m := by
  classical
  conv_lhs =>
    rw [← DirectSum.sum_support_decompose 𝓐 a,
      Finset.sum_smul, DirectSum.decompose_sum, DFinsupp.finsetSum_apply,
      AddSubmonoidClass.coe_finsetSum]
  by_cases hde : d - e ∈ (DirectSum.decompose 𝓐 a).support
  · rw [Finset.sum_eq_single (d - e)]
    · have hmem := SetLike.GradedSMul.smul_mem
        (DirectSum.decompose 𝓐 a (d - e)).property hm
      change _ ∈ ℳ ((d - e) + e) at hmem
      have hdegree : (d - e) + e = d := by omega
      rw [hdegree] at hmem
      exact DirectSum.decompose_of_mem_same ℳ hmem
    · intro i hi hid
      have hmem := SetLike.GradedSMul.smul_mem
        (DirectSum.decompose 𝓐 a i).property hm
      have hne : i +ᵥ e ≠ d := by
        change i + e ≠ d
        omega
      exact DirectSum.decompose_of_mem_ne ℳ hmem hne
    · exact fun hnot => (hnot hde).elim
  · rw [DFinsupp.notMem_support_iff.mp hde]
    simp only [ZeroMemClass.coe_zero, zero_smul]
    apply Finset.sum_eq_zero
    intro i hi
    have hmem := SetLike.GradedSMul.smul_mem
      (DirectSum.decompose 𝓐 a i).property hm
    have hne : i +ᵥ e ≠ d := by
      change i + e ≠ d
      intro hieq
      apply hde
      have : i = d - e := by omega
      rwa [← this]
    exact DirectSum.decompose_of_mem_ne ℳ hmem hne

omit [IsScalarTower R A M] in
/-- The annihilator of an integer-graded module is a homogeneous ideal. -/
theorem annihilator_isHomogeneous
    (ℳ : ℤ → Submodule R M) [DirectSum.Decomposition ℳ]
    [SetLike.GradedSMul 𝓐 ℳ] :
    (Module.annihilator A M).IsHomogeneous 𝓐 := by
  classical
  intro i a ha
  rw [Module.mem_annihilator] at ha ⊢
  intro m
  rw [← DirectSum.sum_support_decompose ℳ m, Finset.smul_sum]
  apply Finset.sum_eq_zero
  intro j hj
  have hzero : a • (DirectSum.decompose ℳ m j : M) = 0 := ha _
  have hcomponent := congrArg
    (fun x : M => ((DirectSum.decompose ℳ x (i + j) : ℳ (i + j)) : M)) hzero
  rw [coe_decompose_smul_of_mem 𝓐 ℳ a
      (DirectSum.decompose ℳ m j).property,
    DirectSum.decompose_zero] at hcomponent
  rw [show i + j - j = i by omega] at hcomponent
  exact hcomponent

omit [IsScalarTower R A M] in
/-- The annihilator of one homogeneous element is homogeneous. -/
theorem torsionOf_isHomogeneous {m : M} {l : ℤ} (hm : m ∈ ℳ l) :
    (Ideal.torsionOf A M m).IsHomogeneous 𝓐 := by
  intro i a ha
  rw [Ideal.mem_torsionOf_iff] at ha ⊢
  have hcomponent := congrArg
    (fun x : M => ((DirectSum.decompose ℳ x (i + l) : ℳ (i + l)) : M)) ha
  rw [coe_decompose_smul_of_mem 𝓐 ℳ a hm,
    DirectSum.decompose_zero] at hcomponent
  rw [show i + l - l = i by omega] at hcomponent
  exact hcomponent

/-- The annihilator of a nonzero element is proper. -/
theorem torsionOf_ne_top_of_ne_zero {m : M} (hm : m ≠ 0) :
    Ideal.torsionOf A M m ≠ ⊤ :=
  (Ideal.torsionOf_eq_top_iff A m).not.mpr hm

/-- The cyclic submodule generated by a homogeneous element, packaged as a
homogeneous submodule. -/
noncomputable def gradedCyclicSubmodule {m : M} {l : ℤ} (hm : m ∈ ℳ l) :
    HomogeneousSubmodule 𝓐 ℳ where
  toSubmodule := Submodule.span A {m}
  is_homogeneous' := by
    intro d x hx
    rw [Submodule.mem_span_singleton] at hx
    obtain ⟨a, rfl⟩ := hx
    rw [coe_decompose_smul_of_mem 𝓐 ℳ a hm]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self m)

/-- The homogeneous annihilator of a homogeneous element, packaged as a
homogeneous submodule of the graded ring so that its quotient inherits a
grading. -/
noncomputable def gradedTorsionSubmodule {m : M} {l : ℤ} (hm : m ∈ ℳ l) :
    HomogeneousSubmodule 𝓐 𝓐 where
  toSubmodule := Ideal.torsionOf A M m
  is_homogeneous' := torsionOf_isHomogeneous 𝓐 ℳ hm

/-- A cyclic module generated by a homogeneous element of degree `l` is
graded-linearly equivalent to the quotient by its annihilator, twisted by
`-l`. -/
noncomputable def gradedCyclicModuleEquiv {m : M} {l : ℤ} (hm : m ∈ ℳ l) :
    GradedLinearEquiv A
      (gradedModuleTwist
        (gradedQuotientPiece 𝓐 𝓐 (gradedTorsionSubmodule 𝓐 ℳ hm)) (-l))
      (gradedSubmodulePiece 𝓐 ℳ (gradedCyclicSubmodule 𝓐 ℳ hm)) where
  toLinearEquiv := by
    change (A ⧸ Ideal.torsionOf A M m) ≃ₗ[A] A ∙ m
    exact Ideal.quotTorsionOfEquivSpanSingleton A M m
  map_piece d := by
    ext y
    constructor
    · rintro ⟨x, hx, rfl⟩
      change x ∈ gradedQuotientPiece 𝓐 𝓐
        (gradedTorsionSubmodule 𝓐 ℳ hm) (d - l) at hx
      obtain ⟨a, ha, rfl⟩ := hx
      change a • m ∈ ℳ d
      have hsmul := SetLike.GradedSMul.smul_mem ha hm
      change a • m ∈ ℳ ((d - l) + l) at hsmul
      have hdegree : (d - l) + l = d := by omega
      rwa [hdegree] at hsmul
    · intro hy
      change (y : M) ∈ ℳ d at hy
      obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp y.property
      let a' : A := DirectSum.decompose 𝓐 a (d - l)
      have ha' : a' • m = (y : M) := by
        calc
          a' • m = ((DirectSum.decompose ℳ (a • m) d : ℳ d) : M) :=
            (coe_decompose_smul_of_mem 𝓐 ℳ a hm).symm
          _ = ((DirectSum.decompose ℳ (y : M) d : ℳ d) : M) := by rw [ha]
          _ = y := DirectSum.decompose_of_mem_same ℳ hy
      refine ⟨Submodule.Quotient.mk a', ?_, ?_⟩
      · change Submodule.Quotient.mk a' ∈ gradedQuotientPiece 𝓐 𝓐
          (gradedTorsionSubmodule 𝓐 ℳ hm) (d - l)
        exact ⟨a', (DirectSum.decompose 𝓐 a (d - l)).property, rfl⟩
      · apply Subtype.ext
        exact ha'

end

end Hartshorne
