/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Rational.HypersurfacePresentation
import Hartshorne.Rational.ProjectiveClosure
import Hartshorne.Rational.VarietyDimension
import Mathlib.Algebra.MvPolynomial.NoZeroDivisors

/-!
# Every variety is birational to a projective hypersurface

Hartshorne, *Algebraic Geometry*, I.4, Proposition 4.9.

For a separated variety with an affine-open basis, its function field has a
presentation by one irreducible equation in `r + 1` affine variables, where
`r` is its transcendence degree.  Homogenizing that equation and taking the
projective closure gives a projective hypersurface in `ℙ^(r+1)` with the same
function field, hence birational to the original variety.

## Main result

* `Hartshorne.exists_birational_projective_hypersurface`
-/

namespace Hartshorne

open MvPolynomial CategoryTheory

variable {k : Type} [Field k] [IsAlgClosed k]
  {τ : Type} [Finite τ] [DecidableEq τ]

omit [Finite τ] in
private theorem homogenize_mul_of_left_ne_zero (i : τ)
    (f g : MvPolynomial {j : τ // j ≠ i} k) (hf : f ≠ 0) :
    homogenize i (f * g) = homogenize i f * homogenize i g := by
  by_cases hg : g = 0
  · subst g
    simp [homogenize]
  have hdeg : (f * g).totalDegree = f.totalDegree + g.totalDegree :=
    MvPolynomial.totalDegree_mul_of_isDomain hf hg
  have hl := homogenize_isHomogeneous i (f * g)
  rw [hdeg] at hl
  have hr := (homogenize_isHomogeneous i f).mul
    (homogenize_isHomogeneous i g)
  apply sub_eq_zero.mp
  apply eq_zero_of_dehomogenize_eq_zero (hl.sub hr)
  rw [map_sub, map_mul, dehomogenize_homogenize, dehomogenize_homogenize,
    dehomogenize_homogenize, sub_self]

omit [Finite τ] in
private theorem span_homogenize_principal (i : τ)
    (f : MvPolynomial {j : τ // j ≠ i} k) (hf : f ≠ 0) :
    Ideal.span (homogenize i ''
      ((Ideal.span {f} : Ideal (MvPolynomial {j : τ // j ≠ i} k)) : Set _)) =
      Ideal.span ({homogenize i f} : Set (MvPolynomial τ k)) := by
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨g, hg, rfl⟩
    obtain ⟨a, rfl⟩ := Ideal.mem_span_singleton.mp hg
    rw [homogenize_mul_of_left_ne_zero i f a hf]
    exact Ideal.mem_span_singleton.mpr ⟨homogenize i a, rfl⟩
  · rw [Ideal.span_le]
    rintro _ rfl
    exact Ideal.subset_span ⟨f, Ideal.mem_span_singleton_self f, rfl⟩

private theorem isAffineVariety_zeroSet_singleton_of_irreducible
    {σ : Type} [Finite σ] {f : MvPolynomial σ k} (hf : Irreducible f) :
    IsAffineVariety (zeroSet ({f} : Set (MvPolynomial σ k))) := by
  let Z := zeroSet ({f} : Set (MvPolynomial σ k))
  have hfne : f ≠ 0 := hf.ne_zero
  have hprime : (Ideal.span {f}).IsPrime :=
    (Ideal.span_singleton_prime hfne).2
      (UniqueFactorizationMonoid.irreducible_iff_prime.1 hf)
  have hvi : vanishingIdeal k Z = Ideal.span {f} := by
    have hspan : Z = zeroSet ((Ideal.span {f} : Ideal (MvPolynomial σ k)) :
        Set (MvPolynomial σ k)) := by
      change zeroSet ({f} : Set (MvPolynomial σ k)) = _
      rw [zeroSet_eq_zeroLocus_span, zeroLocus_eq_zeroSet]
    rw [hspan, vanishingIdeal_zeroSet_eq_radical, hprime.radical]
  refine ⟨(isIrreducible_iff_isPrime (isAlgebraicSet_zeroSet {f})).2 ?_,
    isClosed_zeroSet {f}⟩
  rw [hvi]
  exact hprime

/-- The homogeneous ideal of the closure of an irreducible affine
hypersurface is generated by the homogenized defining equation. -/
theorem homogeneousVanishingIdeal_projectiveClosure_hypersurface
    (i : τ) (f : MvPolynomial {j : τ // j ≠ i} k) (hf : Irreducible f) :
    homogeneousVanishingIdeal
        (projectiveClosure i (zeroSet ({f} : Set (MvPolynomial _ k)))) =
      Ideal.span ({homogenize i f} : Set (MvPolynomial τ k)) := by
  rw [homogeneousVanishingIdeal_projectiveClosure]
  have hfne : f ≠ 0 := hf.ne_zero
  have hprime : (Ideal.span {f}).IsPrime :=
    (Ideal.span_singleton_prime hfne).2
      (UniqueFactorizationMonoid.irreducible_iff_prime.1 hf)
  have hvi : vanishingIdeal k
      (zeroSet ({f} : Set (MvPolynomial {j : τ // j ≠ i} k))) =
        Ideal.span {f} := by
    have hspan : zeroSet ({f} : Set (MvPolynomial {j : τ // j ≠ i} k)) =
        zeroSet ((Ideal.span {f} : Ideal (MvPolynomial {j : τ // j ≠ i} k)) :
          Set (MvPolynomial {j : τ // j ≠ i} k)) := by
      rw [zeroSet_eq_zeroLocus_span, zeroLocus_eq_zeroSet]
    rw [hspan, vanishingIdeal_zeroSet_eq_radical, hprime.radical]
  rw [hvi, span_homogenize_principal i f hfne]

/-- The projective closure of an irreducible affine hypersurface is the
projective hypersurface cut out by its homogenization. -/
theorem projectiveClosure_zeroSet_eq_projZeroSet_homogenize
    (i : τ) (f : MvPolynomial {j : τ // j ≠ i} k) (hf : Irreducible f) :
    projectiveClosure i (zeroSet ({f} : Set (MvPolynomial _ k))) =
      projZeroSet ({homogenize i f} : Set (MvPolynomial τ k)) := by
  let hZ := isAffineVariety_zeroSet_singleton_of_irreducible hf
  let H := projectiveClosure i
    (zeroSet ({f} : Set (MvPolynomial {j : τ // j ≠ i} k)))
  have hH : IsProjVariety H := projectiveClosure_isProjVariety i hZ
  calc
    H = projZeroSet (homogeneousVanishingIdeal H : Set (MvPolynomial τ k)) :=
      hH.isProjAlgebraicSet.projZeroSet_homogeneousVanishingIdeal_eq.symm
    _ = projZeroSet
        (Ideal.span ({homogenize i f} : Set (MvPolynomial τ k)) :
          Set (MvPolynomial τ k)) := by
      rw [homogeneousVanishingIdeal_projectiveClosure_hypersurface i f hf]
    _ = projZeroSet ({homogenize i f} : Set (MvPolynomial τ k)) :=
      projZeroSet_span _

/-- Projective closure preserves the dimension of an affine variety. -/
theorem projDim_projectiveClosure (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    projDim (projectiveClosure i Y) = dim Y := by
  rw [projDim_eq_dim_chart (projectiveClosure_isProjVariety i hY) i
    (projectiveClosure_inter_standardChart_nonempty i hY),
    chartMap_image_projectiveClosure_inter_standardChart i hY]

private theorem birational_projectiveClosure_of_affineFunctionFieldAlgEquiv
    (X : SeparatedVariety k)
    (hXaff : X.toVariety.HasAffineOpenBasis) (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y)
    (e : FunctionField hY.isIrreducible ≃ₐ[k]
      X.toVariety.FunctionField) :
    Birational X
      ⟨Variety.ofProjective (projectiveClosure_isProjVariety i hY),
        isSeparated_ofQuasiProjective
          (projectiveClosure_isProjVariety i hY).isQuasiProjVariety⟩ := by
  let e' : X.toVariety.FunctionField ≃ₐ[k]
      (Variety.ofQuasiAffine hY.isQuasiAffineVariety).FunctionField :=
    ((RationalMapFunctionField.functionFieldAlgEquivAffine
      hY.isQuasiAffineVariety).trans e).symm
  let A : SeparatedVariety k :=
    ⟨Variety.ofQuasiAffine hY.isQuasiAffineVariety,
      RationalMapFunctionField.isSeparated_ofQuasiAffine hY.isQuasiAffineVariety⟩
  let P : SeparatedVariety k :=
    ⟨Variety.ofProjective (projectiveClosure_isProjVariety i hY),
      isSeparated_ofQuasiProjective
        (projectiveClosure_isProjVariety i hY).isQuasiProjVariety⟩
  have hXA : Birational X A :=
    (birational_iff_nonempty_functionField_algEquiv X A hXaff
      (Variety.hasAffineOpenBasis_ofAffine hY)).2 ⟨e'⟩
  have hPA : Birational P A := birational_projectiveClosure i hY
  obtain ⟨eXA⟩ := hXA
  obtain ⟨ePA⟩ := hPA
  exact ⟨eXA.trans ePA.symm⟩

private theorem birational_projective_hypersurface_of_affine_data
    (X : SeparatedVariety k)
    (hXaff : X.toVariety.HasAffineOpenBasis) (r : ℕ)
    (f : MvPolynomial {j : Fin (r + 2) // j ≠ 0} k)
    (hf : Irreducible f)
    (hZ : IsAffineVariety
      (zeroSet ({f} : Set (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k))))
    (hdim : dim
      (zeroSet ({f} : Set (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k))) =
        (r : WithBot ℕ∞))
    (e : FunctionField hZ.isIrreducible ≃ₐ[k]
      X.toVariety.FunctionField) :
    let H := projectiveClosure (0 : Fin (r + 2))
      (zeroSet ({f} : Set (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k)))
    IsProjVariety H ∧
      H = projZeroSet ({homogenize (0 : Fin (r + 2)) f} :
        Set (MvPolynomial (Fin (r + 2)) k)) ∧
      (homogenize (0 : Fin (r + 2)) f).IsHomogeneous f.totalDegree ∧
      projDim H = (r : WithBot ℕ∞) ∧
      Birational X
        ⟨Variety.ofProjective (projectiveClosure_isProjVariety (0 : Fin (r + 2)) hZ),
          isSeparated_ofQuasiProjective
            (projectiveClosure_isProjVariety
              (0 : Fin (r + 2)) hZ).isQuasiProjVariety⟩ := by
  dsimp only
  refine ⟨projectiveClosure_isProjVariety (0 : Fin (r + 2)) hZ,
    projectiveClosure_zeroSet_eq_projZeroSet_homogenize
      (0 : Fin (r + 2)) f hf,
    homogenize_isHomogeneous (0 : Fin (r + 2)) f, ?_, ?_⟩
  · exact (projDim_projectiveClosure (0 : Fin (r + 2)) hZ).trans hdim
  · exact birational_projectiveClosure_of_affineFunctionFieldAlgEquiv
      X hXaff (0 : Fin (r + 2)) hZ e

/-- **Hartshorne I.4, Proposition 4.9.** A separated variety with an
affine-open basis is birational to an irreducible projective hypersurface in
`ℙ^(r+1)`, where `r` is the transcendence degree of its function field.  The
hypersurface has projective dimension `r`. -/
theorem exists_birational_projective_hypersurface
    (X : SeparatedVariety k)
    (hXaff : X.toVariety.HasAffineOpenBasis) (r : ℕ)
    (hdim : topologicalKrullDim X.toVariety.carrier =
      (r : WithBot ℕ∞)) :
    ∃ (f : MvPolynomial {j : Fin (r + 2) // j ≠ 0} k)
      (hZ : IsAffineVariety
        (zeroSet ({f} : Set
          (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k)))),
      Irreducible f ∧
      let H := projectiveClosure (0 : Fin (r + 2))
        (zeroSet ({f} : Set
          (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k)))
      IsProjVariety H ∧
        H = projZeroSet ({homogenize (0 : Fin (r + 2)) f} :
          Set (MvPolynomial (Fin (r + 2)) k)) ∧
        (homogenize (0 : Fin (r + 2)) f).IsHomogeneous f.totalDegree ∧
        projDim H = (r : WithBot ℕ∞) ∧
        Birational X
          ⟨Variety.ofProjective
              (projectiveClosure_isProjVariety (0 : Fin (r + 2)) hZ),
            isSeparated_ofQuasiProjective
              (projectiveClosure_isProjVariety
                (0 : Fin (r + 2)) hZ).isQuasiProjVariety⟩ := by
  let _ : Algebra.EssFiniteType k X.toVariety.FunctionField :=
    RationalMapFunctionField.essFiniteType_functionField hXaff
  have htr := hXaff.trdeg_eq_of_topologicalKrullDim_eq hdim
  obtain ⟨d, f, hf, hdtr, hZ, hZdim, ⟨e⟩⟩ :=
    exists_chart_hypersurface_functionField_algEquiv
      k X.toVariety.FunctionField
  have hdr : d = r := by
    exact_mod_cast hdtr.trans htr
  subst d
  refine ⟨f, hZ, hf, ?_⟩
  exact birational_projective_hypersurface_of_affine_data
    X hXaff r f hf hZ hZdim e

end Hartshorne
