/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Rational.SeparablyGenerated
import Hartshorne.Affine.HypersurfaceDimension
import Hartshorne.Rational.RationalMapFunctionFieldEquivalence

/-!
# Hypersurface presentations of finitely generated fields

The field-theoretic core of Hartshorne, *Algebraic Geometry*, I.4,
Proposition 4.9.

An essentially finitely generated extension of an algebraically closed field
has a separating transcendence basis and one primitive algebraic generator.
Evaluating a polynomial ring at those generators gives a height-one prime
kernel, hence a principal kernel generated by an irreducible polynomial.  The
resulting affine hypersurface has the prescribed function field and dimension.

## Main result

* `Hartshorne.exists_chart_hypersurface_functionField_algEquiv`
-/

open IntermediateField MvPolynomial

namespace Hartshorne

universe u

variable {k K : Type u} [Field k] [Field K] [Algebra k K]

private theorem isFractionRing_quotient_ker_aeval_of_adjoin_eq_top
    {ι : Type u} (x : ι → K)
    (hx : IntermediateField.adjoin k (Set.range x) = ⊤) :
    let e : MvPolynomial ι k →ₐ[k] K := MvPolynomial.aeval x
    let Q := MvPolynomial ι k ⧸ RingHom.ker e
    let qev : Q →ₐ[k] K := Ideal.kerLiftAlg e
    @IsFractionRing Q inferInstance K inferInstance qev.toRingHom.toAlgebra := by
  let e : MvPolynomial ι k →ₐ[k] K := MvPolynomial.aeval x
  let Q := MvPolynomial ι k ⧸ RingHom.ker e
  let qev : Q →ₐ[k] K := Ideal.kerLiftAlg e
  let _ : Algebra Q K := qev.toRingHom.toAlgebra
  let _ : FaithfulSMul Q K :=
    (faithfulSMul_iff_algebraMap_injective Q K).2
      (Ideal.kerLiftAlg_injective e)
  apply IsFractionRing.of_field Q K
  intro z
  have hz : z ∈ IntermediateField.adjoin k (Set.range x) := by
    rw [hx]
    trivial
  obtain ⟨p, q, hpq⟩ := (IntermediateField.mem_adjoin_range_iff k x z).1 hz
  refine ⟨Ideal.Quotient.mk (RingHom.ker e) p,
    Ideal.Quotient.mk (RingHom.ker e) q, ?_⟩
  change z = qev (Ideal.Quotient.mk (RingHom.ker e) p) /
    qev (Ideal.Quotient.mk (RingHom.ker e) q)
  rw [Ideal.kerLiftAlg_mk, Ideal.kerLiftAlg_mk]
  exact hpq

private theorem exists_irreducible_hypersurface_presentation_of_basis
    (s : Finset K) (y : K)
    (hgen : IntermediateField.adjoin k (Set.insert y (s : Set K)) = ⊤)
    (hcard : (s.card : Cardinal) = Algebra.trdeg k K) :
    ∃ f : MvPolynomial (Option s) k,
      Irreducible f ∧
      Nonempty
        (FractionRing
            (MvPolynomial (Option s) k ⧸ Ideal.span ({f} : Set _)) ≃ₐ[k] K) := by
  classical
  let x : Option s → K := fun o => o.elim y ((↑) : s → K)
  have hrange : Set.range x = Set.insert y (s : Set K) := by
    ext z
    constructor
    · rintro ⟨_ | i, rfl⟩
      · exact Set.mem_insert _ _
      · exact Set.mem_insert_of_mem _ i.2
    · intro hz
      rcases hz with (rfl | hz)
      · exact ⟨none, rfl⟩
      · exact ⟨some ⟨z, hz⟩, rfl⟩
  have hxgen : IntermediateField.adjoin k (Set.range x) = ⊤ := by
    rw [hrange]
    exact hgen
  let A := MvPolynomial (Option s) k
  let e : A →ₐ[k] K := MvPolynomial.aeval x
  let P : Ideal A := RingHom.ker e
  have hP : P.IsPrime := RingHom.ker_isPrime e
  let Q := A ⧸ P
  let qev : Q →ₐ[k] K := Ideal.kerLiftAlg e
  let _ : Algebra Q K := qev.toRingHom.toAlgebra
  let _ : IsScalarTower k Q K :=
    IsScalarTower.of_algebraMap_eq fun c => by
      change algebraMap k K c = qev (algebraMap k Q c)
      exact (qev.commutes c).symm
  let _ : IsFractionRing Q K := by
    simpa [A, e, P, Q, qev] using
      (isFractionRing_quotient_ker_aeval_of_adjoin_eq_top x hxgen)
  have _ : FiniteRingKrullDim A := finiteRingKrullDim_of_finiteType k A
  obtain ⟨h, hh⟩ : ∃ h : ℕ, P.height = h :=
    ENat.ne_top_iff_exists.mp (P.height_ne_top hP.ne_top) |>.imp fun _ heq => heq.symm
  obtain ⟨d, hdQ, htr⟩ := exists_ringKrullDim_eq_trdeg k Q K
  have hds : d = s.card := by
    have hcast : (s.card : Cardinal) = (d : Cardinal) := hcard.trans htr
    exact_mod_cast hcast.symm
  have hdimA :
      ringKrullDim A = ((s.card + 1 : ℕ) : WithBot ℕ∞) := by
    change ringKrullDim (MvPolynomial (Option s) k) =
      ((s.card + 1 : ℕ) : WithBot ℕ∞)
    rw [MvPolynomial.ringKrullDim_of_isNoetherianRing,
      ringKrullDim_eq_zero_of_field]
    simp
  have hform := height_add_ringKrullDim_quotient_eq k A P h hh
  have hh1 : h = 1 := by
    rw [hdQ, hds, hdimA] at hform
    have hcast :
        (h : WithBot ℕ∞) + (s.card : WithBot ℕ∞) =
          ((h + s.card : ℕ) : WithBot ℕ∞) := by
      push_cast
      ring
    rw [hcast] at hform
    have hnat : h + s.card = s.card + 1 := by
      exact_mod_cast hform
    omega
  have hPheight : P.height = 1 := by
    rw [hh]
    exact_mod_cast hh1
  obtain ⟨f, hf⟩ :=
    (UniqueFactorizationMonoid.isPrincipal_of_height_eq_one
      (p := P) hPheight).principal
  rw [Ideal.submodule_span_eq] at hf
  have hfne : f ≠ 0 := by
    rintro rfl
    exact Ideal.ne_bot_of_height_eq_one hPheight (by simpa using hf)
  have hspanprime : (Ideal.span ({f} : Set A)).IsPrime := by
    rw [← hf]
    infer_instance
  have hfirr : Irreducible f :=
    (UniqueFactorizationMonoid.irreducible_iff_prime).2
      ((Ideal.span_singleton_prime hfne).1 hspanprime)
  refine ⟨f, hfirr, ?_⟩
  let eQ : Q ≃ₐ[k] (A ⧸ Ideal.span ({f} : Set A)) :=
    Ideal.quotientEquivAlgOfEq k hf
  let eFrac : K ≃ₐ[k] FractionRing (A ⧸ Ideal.span ({f} : Set A)) :=
    IsFractionRing.algEquivOfAlgEquiv eQ
  exact ⟨eFrac.symm⟩

private theorem exists_irreducible_hypersurface_fractionRing_algEquiv
    (k K : Type u) [Field k] [Field K] [Algebra k K]
    [PerfectField k] [Algebra.EssFiniteType k K] :
    ∃ (r : ℕ) (f : MvPolynomial (Fin (r + 1)) k),
      Irreducible f ∧
      (r : Cardinal) = Algebra.trdeg k K ∧
      Nonempty
        (FractionRing
            (MvPolynomial (Fin (r + 1)) k ⧸ Ideal.span ({f} : Set _)) ≃ₐ[k] K) := by
  classical
  obtain ⟨s, y, -, -, -, hgen, hcard⟩ :=
    exists_separatingTranscendenceBasis_and_primitiveElement k K
  obtain ⟨f, hf, ⟨ef⟩⟩ :=
    exists_irreducible_hypersurface_presentation_of_basis s y hgen hcard
  let idxEquiv : Option s ≃ Fin (s.card + 1) :=
    Fintype.equivFinOfCardEq (by simp)
  let ren : MvPolynomial (Option s) k ≃ₐ[k]
      MvPolynomial (Fin (s.card + 1)) k :=
    MvPolynomial.renameEquiv k idxEquiv
  let g : MvPolynomial (Fin (s.card + 1)) k := ren f
  have hg : Irreducible g := hf.map ren
  let I : Ideal (MvPolynomial (Option s) k) := Ideal.span ({f} : Set _)
  let J : Ideal (MvPolynomial (Fin (s.card + 1)) k) := Ideal.span ({g} : Set _)
  have hIJ : J = I.map ren.toRingEquiv.toRingHom := by
    simp [I, J, g, Ideal.map_span]
  let eQ :
      (MvPolynomial (Option s) k ⧸ I) ≃ₐ[k]
        (MvPolynomial (Fin (s.card + 1)) k ⧸ J) :=
    Ideal.quotientEquivAlg I J ren hIJ
  let eFrac :
      FractionRing (MvPolynomial (Option s) k ⧸ I) ≃ₐ[k]
        FractionRing (MvPolynomial (Fin (s.card + 1)) k ⧸ J) :=
    IsFractionRing.algEquivOfAlgEquiv eQ
  refine ⟨s.card, g, hg, hcard, ?_⟩
  exact ⟨eFrac.symm.trans ef⟩

private theorem affine_hypersurface_data_of_fractionRing_algEquiv
    {τ : Type} [Finite τ]
    (k K : Type u) [Field k] [IsAlgClosed k] [Field K] [Algebra k K]
    {r : ℕ} {f : MvPolynomial τ k} (hf : Irreducible f)
    (hcard : (r : Cardinal) = Algebra.trdeg k K)
    (ef : FractionRing
        (MvPolynomial τ k ⧸ Ideal.span ({f} : Set _)) ≃ₐ[k] K) :
    ∃ hZ : IsAffineVariety
        (zeroSet ({f} : Set (MvPolynomial τ k))),
      dim (zeroSet ({f} : Set (MvPolynomial τ k))) =
          (r : WithBot ℕ∞) ∧
      Nonempty (FunctionField hZ.isIrreducible ≃ₐ[k] K) := by
  classical
  have hfne : f ≠ 0 := hf.ne_zero
  have hprime : (Ideal.span ({f} : Set _)).IsPrime :=
    (Ideal.span_singleton_prime hfne).2
      ((UniqueFactorizationMonoid.irreducible_iff_prime).1 hf)
  let Z := zeroSet ({f} : Set (MvPolynomial τ k))
  have hZ : IsAffineVariety Z := by
    rw [show Z = zeroLocus k (Ideal.span ({f} : Set _)) by
      exact zeroSet_eq_zeroLocus_span _]
    exact isAffineVariety_zeroLocus_of_isPrime hprime
  have hvi : vanishingIdeal k Z = Ideal.span ({f} : Set _) := by
    rw [show Z = zeroLocus k (Ideal.span ({f} : Set _)) by
      exact zeroSet_eq_zeroLocus_span _]
    exact vanishingIdeal_zeroLocus_of_isPrime hprime
  let ecoord :
      coordinateRing Z ≃ₐ[k]
        (MvPolynomial τ k ⧸ Ideal.span ({f} : Set _)) :=
    Ideal.quotientEquivAlgOfEq k hvi
  let _ : IsDomain (coordinateRing Z) := isDomain_coordinateRing hZ
  let _ : IsFractionRing (coordinateRing Z)
      (FunctionField hZ.isIrreducible) :=
    isFractionRing_functionField hZ.isIrreducible
  let _ : Field (FunctionField hZ.isIrreducible) :=
    IsFractionRing.toField (coordinateRing Z)
  let eFF :
      FunctionField hZ.isIrreducible ≃ₐ[k]
        FractionRing (MvPolynomial τ k ⧸ Ideal.span ({f} : Set _)) :=
    IsFractionRing.algEquivOfAlgEquiv ecoord
  let eK : FunctionField hZ.isIrreducible ≃ₐ[k] K := eFF.trans ef
  obtain ⟨d, hdimRing, htr⟩ :=
    exists_ringKrullDim_eq_trdeg k (coordinateRing Z)
      (FunctionField hZ.isIrreducible)
  have hdr : d = r := by
    have hcast : (d : Cardinal) = (r : Cardinal) :=
      htr.symm.trans (eK.trdeg_eq.trans hcard.symm)
    exact_mod_cast hcast
  have hdim : dim Z = (r : WithBot ℕ∞) := by
    rw [dim_eq_ringKrullDim_coordinateRing hZ.isAlgebraicSet,
      hdimRing, hdr]
  exact ⟨hZ, hdim, ⟨eK⟩⟩

/-- A finitely generated function field is the function field of an irreducible
affine hypersurface in `r + 1` variables, where `r` is its transcendence
degree.  The variables are indexed as the complement of coordinate `0` in
`Fin (r + 2)`, ready for projective closure in `ℙ^(r+1)`. -/
theorem exists_chart_hypersurface_functionField_algEquiv
    (k K : Type u) [Field k] [IsAlgClosed k] [Field K] [Algebra k K]
    [Algebra.EssFiniteType k K] :
    ∃ (r : ℕ)
      (f : MvPolynomial {j : Fin (r + 2) // j ≠ 0} k),
      Irreducible f ∧
      (r : Cardinal) = Algebra.trdeg k K ∧
      ∃ hZ : IsAffineVariety
          (zeroSet ({f} : Set
            (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k))),
        dim (zeroSet ({f} : Set
          (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k))) =
            (r : WithBot ℕ∞) ∧
        Nonempty (FunctionField hZ.isIrreducible ≃ₐ[k] K) := by
  classical
  obtain ⟨r, f, hf, hcard, ⟨ef⟩⟩ :=
    exists_irreducible_hypersurface_fractionRing_algEquiv k K
  let idxEquiv : Fin (r + 1) ≃ {j : Fin (r + 2) // j ≠ 0} :=
    finSuccAboveEquiv (0 : Fin (r + 2))
  let ren : MvPolynomial (Fin (r + 1)) k ≃ₐ[k]
      MvPolynomial {j : Fin (r + 2) // j ≠ 0} k :=
    MvPolynomial.renameEquiv k idxEquiv
  let g : MvPolynomial {j : Fin (r + 2) // j ≠ 0} k := ren f
  have hg : Irreducible g := hf.map ren
  let I : Ideal (MvPolynomial (Fin (r + 1)) k) := Ideal.span ({f} : Set _)
  let J : Ideal (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k) :=
    Ideal.span ({g} : Set _)
  have hIJ : J = I.map ren.toRingEquiv.toRingHom := by
    simp [I, J, g, Ideal.map_span]
  let eQ :
      (MvPolynomial (Fin (r + 1)) k ⧸ I) ≃ₐ[k]
        (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k ⧸ J) :=
    Ideal.quotientEquivAlg I J ren hIJ
  let eFrac :
      FractionRing (MvPolynomial (Fin (r + 1)) k ⧸ I) ≃ₐ[k]
        FractionRing
          (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k ⧸ J) :=
    IsFractionRing.algEquivOfAlgEquiv eQ
  let eg :
      FractionRing
          (MvPolynomial {j : Fin (r + 2) // j ≠ 0} k ⧸ J) ≃ₐ[k] K :=
    eFrac.symm.trans ef
  obtain ⟨hZ, hdim, hff⟩ :=
    affine_hypersurface_data_of_fractionRing_algEquiv
      k K hg hcard eg
  exact ⟨r, g, hg, hcard, hZ, hdim, hff⟩

end Hartshorne
