/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Affine.CoordinateRing
import Mathlib.RingTheory.MvPolynomial.Localization

/-!
# The coordinate ring of the graph hypersurface

Hartshorne, *Algebraic Geometry*, I.4, Lemma 4.2 (p. 25).

For a nonzero polynomial `f`, adjoining a variable subject to the equation
`t * f = 1` gives the localization away from `f`. Over an algebraically closed
field, the defining principal ideal is prime, so the Nullstellensatz identifies
the quotient by that ideal with the coordinate ring of its zero locus.

## Main definitions

* `Hartshorne.graphPolynomial`
* `Hartshorne.graphIdeal`
* `Hartshorne.graphQuotientLocalizationEquiv`
* `Hartshorne.principalOpenCoordinateRingEquiv`
-/

namespace Hartshorne

open MvPolynomial

variable {k : Type*} [Field k] {σ : Type*}

/-- Identify the extra `Option` variable with the left summand. -/
private def optionUnitSumEquiv (σ : Type*) : Option σ ≃ Unit ⊕ σ where
  toFun
    | none => Sum.inl ()
    | some i => Sum.inr i
  invFun
    | Sum.inl _ => none
    | Sum.inr i => some i
  left_inv x := by cases x <;> rfl
  right_inv x := by rcases x with (_ | i) <;> rfl

/-- Split the extra variable from the original variables in a multivariable
polynomial ring. -/
noncomputable def graphPolynomialEquiv :
    MvPolynomial (Option σ) k ≃ₐ[k]
      MvPolynomial Unit (MvPolynomial σ k) :=
  (MvPolynomial.renameEquiv k (optionUnitSumEquiv σ)).trans
    (MvPolynomial.sumAlgEquiv k Unit σ)

@[simp]
theorem graphPolynomialEquiv_X_none :
    graphPolynomialEquiv (k := k) (σ := σ) (X none) = X () := by
  simp [graphPolynomialEquiv, optionUnitSumEquiv]

@[simp]
theorem graphPolynomialEquiv_X_some (i : σ) :
    graphPolynomialEquiv (k := k) (X (some i)) = C (X i) := by
  simp [graphPolynomialEquiv, optionUnitSumEquiv]

@[simp]
theorem graphPolynomialEquiv_rename_some (f : MvPolynomial σ k) :
    graphPolynomialEquiv (k := k) (rename some f) = C f := by
  induction f using MvPolynomial.induction_on with
  | C a => simp [graphPolynomialEquiv]
  | add p q hp hq => simp [hp, hq]
  | mul_X p i hp => simp [hp]

/-- The equation `t * f - 1` defining the graph hypersurface. -/
noncomputable def graphPolynomial (f : MvPolynomial σ k) :
    MvPolynomial (Option σ) k :=
  X none * rename some f - 1

/-- The principal ideal generated by the graph equation `t * f - 1`. -/
noncomputable def graphIdeal (f : MvPolynomial σ k) :
    Ideal (MvPolynomial (Option σ) k) :=
  Ideal.span {graphPolynomial f}

/-- The corresponding principal ideal after separating the extra variable. -/
private noncomputable def localizationPolynomialIdeal (f : MvPolynomial σ k) :
    Ideal (MvPolynomial Unit (MvPolynomial σ k)) :=
  Ideal.span {C f * X () - 1}

/-- Separating the extra variable sends the graph ideal to the standard ideal
presenting the localization away from `f`. -/
theorem graphIdeal_map (f : MvPolynomial σ k) :
    Ideal.map (graphPolynomialEquiv (k := k) (σ := σ)) (graphIdeal f) =
      localizationPolynomialIdeal f := by
  simp [graphIdeal, graphPolynomial, localizationPolynomialIdeal, Ideal.map_span, mul_comm]

/-- The quotient by the graph ideal, with its variables separated. -/
private noncomputable def graphQuotientEquiv (f : MvPolynomial σ k) :
    (MvPolynomial (Option σ) k ⧸ graphIdeal f) ≃ₐ[k]
      (MvPolynomial Unit (MvPolynomial σ k) ⧸ localizationPolynomialIdeal f) :=
  Ideal.quotientEquivAlg (graphIdeal f) (localizationPolynomialIdeal f)
    (graphPolynomialEquiv (k := k) (σ := σ)) (graphIdeal_map f).symm

/-- Adjoining an inverse to `f` is the quotient by the graph equation
`t * f - 1`. -/
noncomputable def graphQuotientLocalizationEquiv (f : MvPolynomial σ k) :
    (MvPolynomial (Option σ) k ⧸ graphIdeal f) ≃ₐ[k] Localization.Away f :=
  (graphQuotientEquiv f).trans
    ((IsLocalization.Away.mvPolynomialQuotientEquiv
      (Localization.Away f) f).restrictScalars k)

/-- If `f` is nonzero, its graph ideal is prime because its quotient is the
domain obtained by localizing away from `f`. -/
theorem graphIdeal_isPrime (f : MvPolynomial σ k) (hf : f ≠ 0) :
    (graphIdeal f).IsPrime := by
  let _ : IsDomain (Localization.Away f) := Localization.Away.isDomain hf
  have hdom : IsDomain (MvPolynomial (Option σ) k ⧸ graphIdeal f) :=
    (graphQuotientLocalizationEquiv f).injective.isDomain
      (graphQuotientLocalizationEquiv f).toRingHom
  exact (Ideal.Quotient.isDomain_iff_prime (graphIdeal f)).1 hdom

section AlgClosed

variable [IsAlgClosed k] [Finite σ]

/-- **Hartshorne, Lemma 4.2.** The coordinate ring of the hypersurface
`Z(t * f - 1)` is canonically the localization of the original polynomial ring
away from `f`. -/
noncomputable def principalOpenCoordinateRingEquiv
    (f : MvPolynomial σ k) (hf : f ≠ 0) :
    coordinateRing (zeroLocus k (graphIdeal f)) ≃ₐ[k] Localization.Away f :=
  (Ideal.quotientEquivAlgOfEq k
    (vanishingIdeal_zeroLocus_of_isPrime (graphIdeal_isPrime f hf))).trans
      (graphQuotientLocalizationEquiv f)

end AlgClosed

end Hartshorne
