/-
Copyright (c) 2026 Hartshorne formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Hartshorne.Rational.BirationalCriterion
import Hartshorne.Morphism.ChartIso
import Hartshorne.Projective.Homogenize
import Hartshorne.Projective.ProjSpaceDimension
import Hartshorne.Projective.VanishingIdeal

/-!
# Projective closure

Hartshorne, *Algebraic Geometry*, I.2, Exercise 2.9(a).

We define the projective closure of a subset of an affine chart and identify
its homogeneous vanishing ideal with the ideal generated by homogenizations
of its affine vanishing ideal.  For an affine variety, the chosen affine chart
of the closure recovers the original variety; in particular, the variety and
its projective closure are birational.

## Main results

* `Hartshorne.homogeneousVanishingIdeal_projectiveClosure`
* `Hartshorne.chartMap_image_projectiveClosure_inter_standardChart`
* `Hartshorne.birational_projectiveClosure`
-/

namespace Hartshorne

open MvPolynomial TopologicalSpace Topology

universe u

variable {k : Type u} [Field k]
  {τ : Type u} [DecidableEq τ]

/-- The closure in projective space of an affine set placed in the `i`th chart. -/
def projectiveClosure (i : τ)
    (Y : Set ({j : τ // j ≠ i} → k)) : Set (ProjectiveSpace k τ) :=
  closure (chartInv i '' Y)

private theorem totalDegree_dehomogenize_le_of_isHomogeneous (i : τ)
    {f : MvPolynomial τ k} {n : ℕ} (hf : f.IsHomogeneous n) :
    (dehomogenize i f).totalDegree ≤ n := by
  let x : τ → MvPolynomial {j : τ // j ≠ i} k :=
    fun j => if h : j = i then 1 else X ⟨j, h⟩
  change (aeval x f).totalDegree ≤ n
  rw [aeval_def, eval₂_eq]
  apply totalDegree_finsetSum_le
  intro d hd
  have hddeg : d.sum (fun _ e => e) = n := by
    simpa [Finsupp.weight_apply, Pi.one_apply, smul_eq_mul] using
      hf (mem_support_iff.1 hd)
  calc
    ((algebraMap k (MvPolynomial {j : τ // j ≠ i} k)) (coeff d f) *
          ∏ j ∈ d.support, x j ^ d j).totalDegree
        ≤ ((algebraMap k (MvPolynomial {j : τ // j ≠ i} k)) (coeff d f)).totalDegree +
            (∏ j ∈ d.support, x j ^ d j).totalDegree :=
          totalDegree_mul _ _
    _ ≤ ∑ j ∈ d.support, (x j ^ d j).totalDegree := by
          change (C (coeff d f) : MvPolynomial {j : τ // j ≠ i} k).totalDegree +
              (∏ j ∈ d.support, x j ^ d j).totalDegree ≤ _
          simp only [totalDegree_C, zero_add]
          exact totalDegree_finsetProd _ _
    _ ≤ ∑ j ∈ d.support, d j := by
          apply Finset.sum_le_sum
          intro j hj
          simp only [x]
          split_ifs
          · simp
          · simp
    _ = n := hddeg

private theorem homogeneous_eq_X_pow_mul_homogenize_dehomogenize [Infinite k]
    (i : τ) {f : MvPolynomial τ k} {n : ℕ} (hf : f.IsHomogeneous n) :
    f = X i ^ (n - (dehomogenize i f).totalDegree) *
      homogenize i (dehomogenize i f) := by
  let g := dehomogenize i f
  have hle : g.totalDegree ≤ n := totalDegree_dehomogenize_le_of_isHomogeneous i hf
  have hrhs :
      (X i ^ (n - g.totalDegree) * homogenize i g : MvPolynomial τ k).IsHomogeneous n := by
    have h := (isHomogeneous_X_pow (k := k) i (n - g.totalDegree)).mul
      (homogenize_isHomogeneous i g)
    rw [Nat.sub_add_cancel hle] at h
    exact h
  apply sub_eq_zero.mp
  apply eq_zero_of_dehomogenize_eq_zero (hf.sub hrhs)
  rw [map_sub, map_mul, map_pow, dehomogenize_X_self, one_pow, one_mul,
    dehomogenize_homogenize, sub_self]

/-- The homogeneous ideal of the projective closure of an affine subset is
generated by the homogenizations of its affine vanishing ideal. -/
theorem homogeneousVanishingIdeal_projectiveClosure [Infinite k]
    (i : τ) (Y : Set ({j : τ // j ≠ i} → k)) :
    homogeneousVanishingIdeal (projectiveClosure i Y) =
      Ideal.span (homogenize i '' (vanishingIdeal k Y : Set _)) := by
  change homogeneousVanishingIdeal (closure (chartInv i '' Y)) = _
  apply le_antisymm
  · rw [homogeneousVanishingIdeal, Ideal.span_le]
    rintro f ⟨⟨n, hfhom⟩, hfvan⟩
    let g := dehomogenize i f
    have hg : g ∈ vanishingIdeal k Y := by
      intro y hy
      change eval y g = 0
      simpa only [g, chartMap_chartInv] using
        (homogeneousVanish_iff_eval_dehomogenize hfhom
          (chartInv_mem_standardChart i y)).1
          (hfvan (chartInv i y) (subset_closure ⟨y, hy, rfl⟩))
    have hgen : homogenize i g ∈
        Ideal.span (homogenize i '' (vanishingIdeal k Y : Set _)) :=
      Ideal.subset_span ⟨g, hg, rfl⟩
    rw [homogeneous_eq_X_pow_mul_homogenize_dehomogenize i hfhom]
    exact Ideal.mul_mem_left _ _ hgen
  · rw [Ideal.span_le]
    rintro f ⟨g, hg, rfl⟩
    rw [homogeneousVanishingIdeal]
    apply Ideal.subset_span
    refine ⟨⟨g.totalDegree, homogenize_isHomogeneous i g⟩, fun P hP => ?_⟩
    have himage : chartInv i '' Y ⊆ projZeroSet ({homogenize i g} : Set _) := by
      rintro _ ⟨y, hy, rfl⟩ q hq
      rw [Set.mem_singleton_iff] at hq
      subst q
      apply (homogeneousVanish_iff_eval_dehomogenize
        (homogenize_isHomogeneous i g) (chartInv_mem_standardChart i y)).2
      rw [dehomogenize_homogenize]
      have hgy : eval y g = 0 := hg y hy
      simpa only [chartMap_chartInv] using hgy
    have hclosed : IsClosed (projZeroSet ({homogenize i g} : Set _)) :=
      isClosed_projZeroSet_of_isHomogeneousSet (by
        rintro q hq
        rw [Set.mem_singleton_iff] at hq
        subst q
        exact ⟨g.totalDegree, homogenize_isHomogeneous i g⟩)
    exact (closure_minimal himage hclosed hP) _ rfl

theorem projectiveClosure_isProjVariety (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    IsProjVariety (projectiveClosure i Y) := by
  refine ⟨?_, isClosed_closure⟩
  exact (hY.isIrreducible.image (chartInv i)
    (continuous_chartInv i).continuousOn).closure

theorem chartInv_image_subset_projectiveClosure (i : τ)
    (Y : Set ({j : τ // j ≠ i} → k)) :
    chartInv i '' Y ⊆ projectiveClosure i Y :=
  subset_closure

theorem projectiveClosure_inter_standardChart_nonempty (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    (projectiveClosure i Y ∩ standardChart i).Nonempty := by
  obtain ⟨y, hy⟩ := hY.isIrreducible.nonempty
  exact ⟨chartInv i y, subset_closure ⟨y, hy, rfl⟩,
    chartInv_mem_standardChart i y⟩

/-- Intersecting the projective closure with its defining chart and taking
affine coordinates recovers the original affine variety. -/
theorem chartMap_image_projectiveClosure_inter_standardChart (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    chartMap i '' (projectiveClosure i Y ∩ standardChart i) = Y := by
  rw [projectiveClosure, ← closure_chartMap_image]
  have himage : chartMap i '' ((chartInv i '' Y) ∩ standardChart i) = Y := by
    ext y
    constructor
    · rintro ⟨P, ⟨⟨z, hz, rfl⟩, -⟩, rfl⟩
      simpa using hz
    · intro hy
      refine ⟨chartInv i y, ⟨⟨y, hy, rfl⟩, chartInv_mem_standardChart i y⟩, ?_⟩
      exact chartMap_chartInv i y
  rw [himage, hY.isClosed.closure_eq]

section AlgClosed

variable [IsAlgClosed k] [Finite τ]

noncomputable def affineVarietyHomOfSetEq {ι : Type u}
    {Y Z : Set (ι → k)} (hY : IsQuasiAffineVariety Y)
    (hZ : IsQuasiAffineVariety Z) (h : Y = Z) :
    VarietyHom (Variety.ofQuasiAffine hY) (Variety.ofQuasiAffine hZ) := by
  subst Z
  exact VarietyHom.id _

omit [IsAlgClosed k] in
theorem affineVarietyHomOfSetEq_isIso {ι : Type u}
    {Y Z : Set (ι → k)} (hY : IsQuasiAffineVariety Y)
    (hZ : IsQuasiAffineVariety Z) (h : Y = Z) :
    (affineVarietyHomOfSetEq hY hZ h).IsIso := by
  subst Z
  exact VarietyHom.isIso_id _

noncomputable def projectiveClosureChartToAffineHom (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    VarietyHom
      (chartTarget k i (projectiveClosure_isProjVariety i hY).isQuasiProjVariety
        (projectiveClosure_inter_standardChart_nonempty i hY))
      (Variety.ofQuasiAffine hY.isQuasiAffineVariety) :=
  affineVarietyHomOfSetEq
    (isQuasiAffineVariety_chartMap_image i
      (projectiveClosure_isProjVariety i hY).isQuasiProjVariety
      (projectiveClosure_inter_standardChart_nonempty i hY))
    hY.isQuasiAffineVariety
    (chartMap_image_projectiveClosure_inter_standardChart i hY)

omit [Finite τ] [IsAlgClosed k] in
theorem projectiveClosureChartToAffineHom_isIso (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    (projectiveClosureChartToAffineHom i hY).IsIso :=
  affineVarietyHomOfSetEq_isIso
    (isQuasiAffineVariety_chartMap_image i
      (projectiveClosure_isProjVariety i hY).isQuasiProjVariety
      (projectiveClosure_inter_standardChart_nonempty i hY))
    hY.isQuasiAffineVariety
    (chartMap_image_projectiveClosure_inter_standardChart i hY)

noncomputable def Variety.topRestrictHom (X : Variety k) :
    VarietyHom X (X.restrict ⊤ Set.univ_nonempty) :=
  VarietyHom.liftToRestrict (VarietyHom.id X) ⊤ Set.univ_nonempty (fun _ => trivial)

omit [IsAlgClosed k] in
theorem Variety.topRestrictHom_isIso (X : Variety k) :
    X.topRestrictHom.IsIso := by
  refine ⟨X.inclHom ⊤ Set.univ_nonempty, ?_, ?_⟩
  · apply VarietyHom.ext
    funext x
    rfl
  · apply VarietyHom.ext
    funext x
    rfl

/-- The closure's standard chart is isomorphic to the original affine variety. -/
theorem projectiveClosure_hasIsomorphicOpenSubsets (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    (Variety.ofProjective (projectiveClosure_isProjVariety i hY)).HasIsomorphicOpenSubsets
      (Variety.ofQuasiAffine hY.isQuasiAffineVariety) := by
  let _ : Nonempty τ := ⟨i⟩
  let hP := projectiveClosure_isProjVariety i hY
  let hne := projectiveClosure_inter_standardChart_nonempty i hY
  let U := projectiveChartOpen hP.isQuasiProjVariety i
  let hU := projectiveChartOpen_nonempty hP.isQuasiProjVariety i hne
  let A := Variety.ofQuasiAffine hY.isQuasiAffineVariety
  let r := restrictChartHom hP.isQuasiProjVariety i hne
  let a := projectiveClosureChartToAffineHom i hY
  let t := A.topRestrictHom
  refine ⟨U, hU, ⊤, Set.univ_nonempty, t.comp (a.comp r), ?_⟩
  exact A.topRestrictHom_isIso.comp
    ((projectiveClosureChartToAffineHom_isIso i hY).comp
      (isIso_restrictChartHom hP.isQuasiProjVariety i hne))

omit [IsAlgClosed k] [Finite τ] in
/-- The affine chart inside the projective closure is dense. -/
theorem projectiveClosure_chart_dense (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    Dense {p : (Variety.ofProjective
      (projectiveClosure_isProjVariety i hY)).carrier |
        p.1 ∈ standardChart i} := by
  apply Variety.dense_of_isOpen_of_nonempty
    ((isOpen_standardChart i).preimage continuous_subtype_val)
  obtain ⟨p, hp, hpi⟩ := projectiveClosure_inter_standardChart_nonempty i hY
  exact ⟨⟨p, hp⟩, hpi⟩

/-- An affine variety is birational to its projective closure. -/
theorem birational_projectiveClosure (i : τ)
    {Y : Set ({j : τ // j ≠ i} → k)} (hY : IsAffineVariety Y) :
    Birational
      ⟨Variety.ofProjective (projectiveClosure_isProjVariety i hY),
        isSeparated_ofQuasiProjective
          (projectiveClosure_isProjVariety i hY).isQuasiProjVariety⟩
      ⟨Variety.ofQuasiAffine hY.isQuasiAffineVariety,
        RationalMapFunctionField.isSeparated_ofQuasiAffine hY.isQuasiAffineVariety⟩ := by
  let _ : Nonempty τ := ⟨i⟩
  let P : SeparatedVariety k :=
    ⟨Variety.ofProjective (projectiveClosure_isProjVariety i hY),
      isSeparated_ofQuasiProjective
        (projectiveClosure_isProjVariety i hY).isQuasiProjVariety⟩
  let A : SeparatedVariety k :=
    ⟨Variety.ofQuasiAffine hY.isQuasiAffineVariety,
      RationalMapFunctionField.isSeparated_ofQuasiAffine hY.isQuasiAffineVariety⟩
  exact ((birational_criterion P A
    (Variety.hasAffineOpenBasis_ofProjective
      (projectiveClosure_isProjVariety i hY))
    (Variety.hasAffineOpenBasis_ofAffine hY)).1).2
      (projectiveClosure_hasIsomorphicOpenSubsets i hY)

end AlgClosed

end Hartshorne
